nodatime/nodatime

src/NodaTime.Demo/StackOverflowExamples.cs
src/NodaTime.Test/DateTimeZoneTest.LocalConversions.cs
src/NodaTime.Test/LocalDateTimeTest.cs
src/NodaTime.Test/Text/ZonedDateTimePatternTest.cs
src/NodaTime.Test/TimeZones/ResolversTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/DateTimeZone.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/TimeZones/Resolvers.cs
www/unstable/userguide/migration-to-2.md
www/unstable/userguide/versions.md

Discussed in #295, this PR does the following:
- Adds a `ReturnForwardShifted` resolver
- Changes the behavior of the `LenientResolver` and associated methods:
- Ambiguous values are now resolved with `ReturnEarlier` instead of `ReturnLater`
- Skipped values are now resolved with `ReturnForwardShifted` instead of `ReturnStartOfInterval`
- Updates associated xml docs and unit tests.
Note that this is a breaking change, which should be described and highlighted in the documentation and release notes when 2.0 is released.  I'm convinced that this is a better default behavior than the existing lenient behavior, based on numerous real-world examples.
My thinking goes like this:
- If you have an ambiguous value, it's probably because you are scheduling a job to run at the same time every day. …

Revisit Resolvers per #295

---

src/NodaTime-Core.sln

These aren't picked up automatically due to the way we pull in the dependencies in the benchmarks project file itself, allowing the multi-version benchmarking.

Add dependencies to benchmarks project in "core" solution.

---

src/NodaTime.Test/Calendars/YearMonthDayCalculatorTest.cs
src/NodaTime/Calendars/HebrewScripturalCalculator.cs

… and fix them when they break.
HebrewYearMonthCalculator was broken for year 0 and earlier - which isn't a problem for
most code, but it's possible that in a few cases our internals need to be able to handle values
outside the normal range. The cache format was assuming it could tweak the two high bits
arbitrarily - which doesn't work so well when the original value is negative. We now use the
bottom two bits for the lengths of Heshvan/Kislev.

Test more calculators in YearMonthCalculatorTest... 

---

src/NodaTime.Test/CalendarSystemTest.cs
src/NodaTime.Test/Calendars/EraTest.cs
src/NodaTime.Test/Calendars/HebrewCalendarSystemTest.cs
src/NodaTime.Test/Calendars/UmAlQuraYearMonthDayCalculatorTest.cs
src/NodaTime.Test/Globalization/NodaFormatInfoTest.cs
src/NodaTime.Test/PeriodTest.cs
src/NodaTime.Test/Text/Cultures.cs
src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime.Test/Text/LocalTimePatternTest.cs
src/NodaTime.Test/Text/OffsetPatternTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneTest.cs

Aside from generally being nicer, it means we can get rid of a bunch of #pragma warning disable directives.

Use nameof with test case sources.

---

src/NodaTime.Test/DateTimeZoneTest.LocalConversions.cs
src/NodaTime/LocalDate.cs

This is a convenience method to call DateTimeZone.AtStartOfDay.
This fixes issue #399.
(I'd be open to other naming suggestions, btw.)
// cc @malcolmr

Implement LocalDate.InZone.

---

src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime/Text/Patterns/DatePatternHelper.cs

Fixes issue #414 for 2.0. Still need a fix for 1.3.x.

Disallow a month number of 0 when parsing

---

src/NodaTime.Test/Text/LocalTimePatternTest.cs
src/NodaTime.Test/Text/ValueCursorTest.cs
src/NodaTime/Text/Patterns/TimePatternHelper.cs
src/NodaTime/Text/PeriodPattern.cs
src/NodaTime/Text/ValueCursor.cs

I would have expected the LocalTime pattern "HHmmssFF" to handle either of these two cases:
(1) "11223344" -> 11:22:33.44
(2) "112233" -> 11:22:33.00
Case 1 works, but case 2 does not.
Some similar cases do work:
"1122334" / "HHmmssFF" -> 11:22:33.4
"112233" / "HHmmss.FF" -> 11:22:33.0
The fix turns out to be pretty easy, as you can see by the diff. The nature of the change (removing an explicit error condition check) made me think that this would cause problems, but all the unit tests still pass, and I haven't been able to think of any cases where I would actually want the old behavior.
If somebody else can think of some cases where the check actually gives good behavior, we should at a minimum add some tests to demonstrate it. If not, you can merge in my change!

Handle completely empty fractional seconds with "F" format specifier.

---

src/NodaTime.Test/InstantTest.cs
src/NodaTime/Instant.cs

Julian Day Numbers are widely used in Astronomical calculations. I added two functions to convert the NodaTime.Instant classes back and forth to and from their JDN.

Added functions to convert Instant to and from Julian Day Numbers

---

src/NodaTime.Test/InstantTest.cs
src/NodaTime.Test/NodaConstantsTest.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime/Instant.cs
src/NodaTime/NodaConstants.cs

This uses Julian Date rather than Julian Day Number as terminology, following
https://en.wikipedia.org/wiki/Julian_day - a Julian Day Number is an integer instead.
Annoying that we don't have a good way of constructing a duration from a double at the moment...

Refactor Julian Date arithmetic

---

src/NodaTime.Test/LocalInstantTest.cs
src/NodaTime/LocalInstant.cs

We only see LocalInstant.ToString() when tests fail - but it really helps if it doesn't throw an exception itself at that point...

Fix LocalInstant.ToString() to use a valid pattern

---

src/NodaTime.Test/LocalInstantTest.cs
src/NodaTime/LocalInstant.cs
src/NodaTime/Text/InstantPatternParser.cs

- Make the value roundtrip by including subsecond information
- Handle BeforeMinValue/AfterMaxValue

Improve LocalInstant.ToString behaviour

---

src/NodaTime.Test/CalendarSystemTest.Validation.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/Calendars/WeekYearCalculator.cs

This suffers the problem we have elsewhere of not really having a min/max week-year... will file an issue.
This fixes issue #437.

Added CalendarSystem.GetWeeksInWeekYear

---

src/NodaTime.Test/Globalization/NodaFormatInfoTest.cs
src/NodaTime.Test/Text/OffsetPatternTest.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/Text/Patterns/SteppedPatternBuilder.cs
www/unstable/userguide/migration-to-2.md
www/unstable/userguide/offset-patterns.md
www/unstable/userguide/versions.md

I'd like to get these two commits in before changing NodaFormatInfo.GetInstance, as the latter change is likely to require more discussion.

Remove uses of NumberFormatInfo and CompareInfo in NodaTimeFormatInfo

---

.travis.yml
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs

Basically Mono doesn't play well with TimeZoneInfo in general. The NUnitLite
test runner fails if there's a test case source with no tests, so here we insert
a dummy one and explicitly use Assert.Ignore so we know the test is ignored.
Core CLR adopting IANA on Linux makes everything that bit trickier - this is
already covered in issue #434.

Fix our Travis build, by skipping tests failing on Mono

---

src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs
src/NodaTime.Test/DurationTest.Construction.cs
src/NodaTime.Test/DurationTest.Operators.cs
src/NodaTime.Test/DurationTest.cs
src/NodaTime/Duration.cs
src/NodaTime/Text/DurationPatternParser.cs
src/NodaTime/project.json

Fixes issue #447.
(Still need to check performance, although relatively few operations will be affected.)

Convert Duration to use BigInteger instead of decimal

---

www/_plugins/userguide.rb
www/index.html
www/unstable/userguide/calendars.md
www/unstable/userguide/installation.md
www/unstable/userguide/limitations.md
www/unstable/userguide/mono.md
www/unstable/userguide/versions.md

(We won't be updating the online user guide, but we ship an offline copy.)
These are all I could find easily, but I'll have another look when I build the package.
(Anything else you can think of that I might have forgotten?)

Remove traces of code.google.com from 1.3 user guide

---

src/NodaTime.Benchmarks/BclTests/DateTimeBenchmarks.cs
src/NodaTime.Benchmarks/BclTests/DateTimeOffsetBenchmarks.cs
src/NodaTime.Benchmarks/BclTests/UtcDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/Calendars/HebrewCalendarBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/InstantBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/OffsetDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/PacificZonedDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/PeriodBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/UtcZonedDateTimeBenchmarks.cs

(Just refactoring - although I had to be careful in one case, with `#ifdef` not being handled properly.)

Use expression-bodied members in benchmarks

---

src/NodaTime.Serialization.JsonNet/NodaConverterBase.cs
src/NodaTime.Serialization.JsonNet/NodaConverters.cs

This isn't pure syntactic refactoring - we had a lot of public static
readonly fields which are now properties.

Update serialization code with C# 6 features

---

src/NodaTime.Benchmarks/NodaTimeTests/Calendars/RegularWeekYearRuleBenchmarks.cs
src/NodaTime.Test/Calendars/IsoCalendarSystemTest.cs
src/NodaTime.Test/Calendars/RegularWeekYearRuleTest.cs
src/NodaTime/Calendars/IWeekYearRule.cs
src/NodaTime/Calendars/RegularWeekYearRule.cs
src/NodaTime/Calendars/WeekYearRule.cs
src/NodaTime/LocalDate.cs

Two-step change to move to WeekYearRule being an interface.
If we're happy with the code here, we can then brush up on the documentation (either as extra commits in this PR or as other PRs). I wanted to get the right shape of the API first though.
// cc @mj1856 for any feedback on abstract class vs interface, and extension methods vs optional parameters.

Week year rule interface

---

src/NodaTime.Benchmarks/project.json

Benchmarks still won't quite run, as BenchmarkDotNet requires dotnet cli
instead of dnx, but we're getting there... 0.9.5 is strongly named.

Update benchmark dependencies

---

src/NodaTime.Serialization.JsonNet/project.json
src/NodaTime.Testing/project.json
src/NodaTime/project.json

(We do need to be slightly careful not to accidentally release a full 2.0.0, but I think it would be pretty odd to "accidentally" do a nuget push...)

Update version number in project.json to be more amenable to creating prereleases

---

src/NodaTime.Test/Calendars/BclCalendars.cs
src/NodaTime.Test/Calendars/BclWeekYearRuleTest.cs
src/NodaTime/Calendars/BclWeekYearRule.cs

It turns out these are pretty simple:
- Either 1, 4 or 7 as the "min days in first week"
- Variable "first day of week"
- Unlike the ISO rules, the end of the calendar year is always in the same
week-year, so the first week of the week-year may be shorter than 7 days.
(The first days of the calendar year *may* be in the previous week-year
though.)
There's a lot of common code between this and RegularWeekYearRule; it shouldn't
be too hard to refactor the code into a single class, providing the ability
for "regular" week year rules to have a variable first day of week too. That
can come later though, along with a whole user guide page with many, many
examples.

Implement BCL week rules.

---

.travis.yml
global.json
src/.nuget/packages.config
src/NodaTime.Benchmarks/project.json
src/NodaTime.Demo/packages.config
src/NodaTime.Demo/project.json
src/NodaTime.Serialization.JsonNet/packages.config
src/NodaTime.Serialization.JsonNet/project.json
src/NodaTime.Serialization.Test/packages.config
src/NodaTime.Serialization.Test/project.json
src/NodaTime.Test/packages.config
src/NodaTime.Test/project.json
src/NodaTime.Testing/project.json
src/NodaTime.TzValidate.NodaDump/project.json
src/NodaTime.TzdbCompiler.Test/packages.config
src/NodaTime.TzdbCompiler.Test/project.json
src/NodaTime.TzdbCompiler/packages.config
src/NodaTime.TzdbCompiler/project.json
src/NodaTime/project.json

Two issues remain:
- Some unmapped time zones (possibly fixed by an override file); probably unrelated to .NET Core
- NodaTime.Serialization.Test fails to execute due to conflicting Json.NET versions

Most of the way to hitting .NET Core 1.0 RTM.

---

src/NodaTime-Web.sln
src/NodaTime.Web/Controllers/TzValidateController.cs
src/NodaTime.Web/Startup.cs
src/NodaTime.Web/project.json

This will fix issue #548 when the web site is rebuilt.
(There are other accidental changes in here too, but they're not problematic.)

Serve .nzd extensions as application/octet-stream

---

src/NodaTime.Testing/project.json

This looks like it's okay now.
Closes #510.

Remove System.Runtime.Numerics dependency from NodaTime.Testing.

---

src/NodaTime.Test/DateTimeZoneTest.GetZoneIntervals.cs
src/NodaTime.TzValidate.NodaDump/ZoneDumper.cs
src/NodaTime/DateTimeZone.cs
src/NodaTime/TimeZones/ZoneEqualityComparer.cs

...  when asking for all the zone intervals in an interval.
This is slightly odd as it reuses an existing enum and not every
option will affect the result, but I think it's okay.
(I needed this for ZoneDumper, and it feels like it's generally useful.)

Add the ability to coalesce zone intervals

---

src/NodaTime.Test/Tests.nunit
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.xproj
src/NodaTime.TzdbCompiler.Test/ProgramTest.cs
src/NodaTime.TzdbCompiler.Test/Tests.nunit
src/NodaTime.TzdbCompiler.Test/Tzdb/CldrWindowsZonesParserTest.cs
src/NodaTime.TzdbCompiler/CompilerOptions.cs
src/NodaTime.TzdbCompiler/Program.cs
src/NodaTime.TzdbCompiler/Tzdb/CldrWindowsZonesParser.cs
src/NodaTime/TimeZones/Cldr/MapZone.cs
src/NodaTime/TimeZones/Cldr/WindowsZones.cs

This fixes #473 in terms of code - process still needs definition.

Add the ability to provide an "override" file for Windows zone mappings

---

src/NodaTime.Benchmarks/project.json

This supports .NET Core, but we still have a "Category" attribute which would probably need an extra dependency; will investigate that separately.

Update to BenchmarkDotNet 0.9.9

---

src/NodaTime/Utility/Preconditions.cs

This significantly improves the Duration.From* performance, but
isn't quite good enough to let us remove the manual optimizations in
the LocalTime constructor and GregorianYearMonthDayCalculator.ValidateGregorianYearMonthDay.
If we could hook into the build process and rewrite the Roslyn tree,
we could perform those optimizations automatically, and even remove
the explicit Preconditions calls entirely, putting everything in
attributes. We're not there yet though :(

Improve Preconditions efficiency

---

docs/userguide/unstable/concepts.md

This is a tiny change to be extra precise about the fact that the help guid talks about winter in the Northern Hemisphere. Being pedantic about time/date is good, right? ;)

Pedantic - added Northern Hemisphere to "winter"

---

src/NodaTime.TzdbCompiler/Program.cs
src/NodaTime.TzdbCompiler/Tzdb/TzdbDatabase.cs
src/NodaTime.TzdbCompiler/Tzdb/TzdbStreamWriter.cs

Two different issues prevented running the TzValidate code directly with an IANA URL.

Fix TzValidate.NodaDump

---

src/NodaTime.Test/DurationTest.Construction.cs
src/NodaTime.Test/DurationTest.cs
src/NodaTime.Test/PeriodTest.cs
src/NodaTime.Test/SystemClockTest.cs
src/NodaTime.TzdbCompiler.Test/Tzdb/TokensTest.cs
src/NodaTime/Duration.cs

- Ticks => BclCompatibleTicks
- ToDoubleNanoseconds() => TotalNanoseconds
- Add TotalMilliseconds
- Fix typos in XML comments
Fixes #402.

Rationalize Duration properties/methods

---

.gitignore
build/appveyor.sh
build/coverage.sh

Also run netcoreapp1.0 rather than net451 tests, to avoid
JIT errors. Not ideal, but better.

Separate running coverage out of AppVeyor script

---

src/NodaTime.Test/DateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/FixedDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/PrecalculatedDateTimeZoneTest.cs
src/NodaTime.Testing/TimeZones/MultiTransitionDateTimeZone.cs
src/NodaTime.Testing/TimeZones/SingleTransitionDateTimeZone.cs
src/NodaTime/DateTimeZone.cs
src/NodaTime/IDateTimeZoneProvider.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/TimeZones/CachedDateTimeZone.cs
src/NodaTime/TimeZones/FixedDateTimeZone.cs
src/NodaTime/TimeZones/PrecalculatedDateTimeZone.cs

IDateTimeZoneProvider is now documented to return equal zones when asked for the same
ID, which CachedDateTimeZoneProvider will do by way of caching for all non-fixed-offset zones, and
regular equality for FixedOffsetDateTimeZone.
Fixes #180.

Use reference equality for time zones other than FixedDateTimeZone

---

docs/developer/tzdb-file-format.md
src/NodaTime.Serialization.JsonNet/project.json
src/NodaTime.Test/Testing/TimeZones/FakeDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/DateTimeZoneCacheTest.cs
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime.Testing/TimeZones/FakeDateTimeZoneSource.cs
src/NodaTime.Testing/project.json
src/NodaTime.TzdbCompiler/Tzdb/PclSupport.cs
src/NodaTime.TzdbCompiler/Tzdb/TzdbStreamWriter.cs
src/NodaTime/TimeZones/BclDateTimeZoneSource.cs
src/NodaTime/TimeZones/DateTimeZoneCache.cs
src/NodaTime/TimeZones/IDateTimeZoneSource.cs
src/NodaTime/TimeZones/IO/TzdbStreamData.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs
src/NodaTime/project.json
www/developer/tzdb-file-format.md

- IDateTimeZoneSource now only exposes GetSystemDefaultId
- Use TimeZoneInfo.Id instead of TimeZoneInfo.StandardName
(requires netstandard1.3)
- Ignore the standard names field when reading NZD files. We
still generate them for 1.x clients.
- If we can't find the local ID as a Windows ID, see if it's already
a TZDB ID
- If we still can't find it, guess based on transitions.
- Fix missing standard name mappings.
Fixes #282.
Fixes #543.
Fixes #434.
(Apologies for several changes in one... they're all inter-related, and it was simpler to do them all in one go.)

Revisit time zone mapping

---

docs/userguide/unstable/migration-to-2.md
docs/userguide/unstable/versions.md
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/OffsetDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/PacificZonedDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/UtcZonedDateTimeBenchmarks.cs
src/NodaTime.Test/Calendars/CopticCalendarSystemTest.cs
src/NodaTime.Test/Calendars/IslamicCalendarSystemTest.cs
src/NodaTime.Test/Calendars/IsoCalendarSystemTest.cs
src/NodaTime.Test/Calendars/SimpleWeekYearRuleTest.cs
src/NodaTime.Test/DateTimeZoneTest.LocalConversions.cs
src/NodaTime.Test/LocalDateTest.BasicProperties.cs
src/NodaTime.Test/LocalDateTimeTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/DateAdjusters.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/Text/LocalDatePatternParser.cs
src/NodaTime/Text/LocalDateTimePatternParser.cs
src/NodaTime/Text/OffsetDateTimePatternParser.cs
src/NodaTime/Text/ZonedDateTimePatternParser.cs
src/NodaTime/TimeZones/ZoneYearOffset.cs
src/NodaTime/ZonedDateTime.cs
www/unstable/userguide/migration-to-2.md
www/unstable/userguide/versions.md

(Numeric versions are removed.)
This is done as several commits for clarity - will preserve them (rather than squashing) when I merge.
I don't *think* we refer to the properties in the user guide...
Fixes #472.

Rename LocalDate.IsoDayOfWeek (et al) to DayOfWeek

---

src/NodaTime.Test/LocalTimeTest.cs
src/NodaTime/LocalTime.cs

Fixes #356.
(I haven't added an `EndOfDay` property in the end; we can do that later if we want, but it does seem a bit over the top.)

Add LocalTime.{MinValue,MaxValue}

---

docs/userguide/unstable/versions.md
src/NodaTime.Test/TimeZones/BclDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/DateTimeZoneCacheTest.cs
src/NodaTime/IDateTimeZoneProvider.cs
src/NodaTime/TimeZones/DateTimeZoneCache.cs
www/unstable/userguide/versions.md

The source is only consulted for IDs it advertises, but that includes ones that are fixed, e.g. "UTC-2".
Fixes #332.

Prefer fixed offset zones from the source rather than FixedOffsetZone

---

src/NodaTime/DateTimeZone.cs

In particular, document that it will be equal to (though not necessarily the same instance as[*]) whatever `DateTimeZone.ForOffset(Offset.Zero)` returns, and clarify that it may not be equal to any zone returned by `IDateTimeZoneProvider["UTC"]` (as after #332 is resolved, it won't be).
Refs #180.
[*] In practice, `DateTimeZone.ForOffset(Offset.Zero)` _will_ be the same instance as `DateTimeZone.Utc` (and we have tests to check that), but it doesn't need to be.

Document guarantees around DateTimeZone.Utc equality.

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

Specifically, add `DateInterval.NormalizingEqualityComparer` and `ContainedDatesEqualityComparer`.
`NormalizingEqualityComparer` additionally considers as equal two intervals that differ only in whether they are closed or half-open (inclusive or exclusive), meaning that [2001-01-01, 2001-01-31] is considered equal to [2001-01-01, 2001-02-01).  However, empty intervals with different start dates are still considered unequal.
(This is documented in terms of normalizing all intervals to exclusive intervals, since that's mathematically simpler; however, in practice we cannot actually represent all inclusive intervals as exclusive, and so we implement this by normalizing in the _other_ direction, then treating empty intervals as a special case.)
`ContainedDatesEqualityComparer` additionally …

Implement additional equality comparers for DateInterval.

---

docs/userguide/unstable/migration-to-2.md
docs/userguide/unstable/versions.md
src/NodaTime.Benchmarks/NodaTimeTests/JsonNet/FormattingBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalTimeBenchmarks.cs
src/NodaTime.Serialization.Test/JsonNet/NodaConvertersTest.cs
src/NodaTime.Test/Calendars/IsoCalendarSystemTest.cs
src/NodaTime.Test/InstantTest.Operators.cs
src/NodaTime.Test/InstantTest.cs
src/NodaTime.Test/IntervalTest.cs
src/NodaTime.Test/LocalDateTimeTest.Pseudomutators.cs
src/NodaTime.Test/LocalDateTimeTest.cs
src/NodaTime.Test/LocalTimeTest.Pseudomutators.cs
src/NodaTime.Test/LocalTimeTest.cs
src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/PeriodTest.cs
src/NodaTime.Test/Text/LocalTimePatternTest.cs
src/NodaTime.Test/TimeAdjustersTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/Instant.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs
www/unstable/userguide/migration-to-2.md
www/unstable/userguide/versions.md

- Convert LocalTime constructors accepting ticks to factory methods
- Remove LocalDateTime constructors accepting ticks
- Add Instant.PlusNanos to match Instant.PlusTicks. (Both are probably still useful.)
Fixes #617, although we should probably look over all core APIs at some point before 2.0.

Address "tick-oriented" APIs

---

build/updatetzdb.bat
src/NodaTime-All.sln
src/NodaTime.TzValidate.NzdCompatibility/NodaTime.TzValidate.NzdCompatibility.xproj
src/NodaTime.TzValidate.NzdCompatibility/Options.cs
src/NodaTime.TzValidate.NzdCompatibility/Program.cs
src/NodaTime.TzValidate.NzdCompatibility/UserErrorException.cs
src/NodaTime.TzValidate.NzdCompatibility/ZoneDumper.cs
src/NodaTime.TzValidate.NzdCompatibility/project.json

This only thoroughly checks the TZDB part of it, but that should be good enough for now.
It will already have loaded the Windows zones etc, but we don't check the data itself.
Fixes #364.

Add compatibility test for Noda Time 1.1 reading NZD files

---

src/NodaTime/TimeZones/Cldr/WindowsZones.cs

Fixes #398.
(At least, I think it's enough to fix 398...)

Document the values of the IDs returned by WindowsZones.PrimaryMapping.

---

src/NodaTime.Test/InstantTest.cs
src/NodaTime.Test/LocalDateTimeTest.cs
src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/Instant.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/ZonedDateTime.cs

- Document and test that we truncate towards the start of time
- Throw an appropriate exception for date/time and offset values
being out of range
- Round offsets towards zero if they have non-zero second values
Fixes #395.

Handle truncation and range issues for BCL conversions.

---

packaging/NodaTime.targets

The ImportGroup condition in NodaTime.targets is not evaluated correctly in Visual Studio 2015. This leads to unresolved reference warnings for C# netstandard projects. The fix for this is to use a Choose/When instead of the ImportGroup condition.
Fixes #632

NodaTime.targets condition fix for Visual Studio

---

www/unstable/userguide/concepts.md

The two should now be in sync (I think) so either is
fine as the basis of investigations into MarkdownViewEngine.

Propagate change from docs to www/unstable/userguide

---

src/NodaTime.Web/Markdown/1.0.x/localdate-patterns.md
src/NodaTime.Web/Markdown/1.0.x/localtime-patterns.md
src/NodaTime.Web/Markdown/1.0.x/offset-patterns.md
src/NodaTime.Web/Markdown/1.0.x/text.md
src/NodaTime.Web/Markdown/1.1.x/localdate-patterns.md
src/NodaTime.Web/Markdown/1.1.x/localtime-patterns.md
src/NodaTime.Web/Markdown/1.1.x/offset-patterns.md
src/NodaTime.Web/Markdown/1.1.x/text.md
src/NodaTime.Web/Markdown/1.2.x/duration-patterns.md
src/NodaTime.Web/Markdown/1.2.x/localdate-patterns.md
src/NodaTime.Web/Markdown/1.2.x/localtime-patterns.md
src/NodaTime.Web/Markdown/1.2.x/offset-patterns.md
src/NodaTime.Web/Markdown/1.2.x/text.md
src/NodaTime.Web/Markdown/1.3.x/duration-patterns.md
src/NodaTime.Web/Markdown/1.3.x/localdate-patterns.md
src/NodaTime.Web/Markdown/1.3.x/localtime-patterns.md
src/NodaTime.Web/Markdown/1.3.x/offset-patterns.md
src/NodaTime.Web/Markdown/1.3.x/text.md
src/NodaTime.Web/Markdown/unstable/duration-patterns.md
src/NodaTime.Web/Markdown/unstable/localdate-patterns.md
src/NodaTime.Web/Markdown/unstable/localtime-patterns.md
src/NodaTime.Web/Markdown/unstable/offset-patterns.md
src/NodaTime.Web/Markdown/unstable/text.md
src/NodaTime.Web/wwwroot/css/main.css

- Remove blank line in localtime-patterns to avoid Markdown
parsing text as code
- Use styling to boost size of example column
Fixes #646.

Improve formatting of text patterns in the user guide

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

This improves clarity - the property *could* still be removed
if #2 is resolved to make all date intervals inclusive.

Rename DateInterval.Inclusive to EndInclusive

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs

(The previous failures now pass, yay, but Windows hasn't caught up
to Mongolia's DST change.)
Fixes #672.

Update the "expected" TZDB guess failures

---

src/NodaTime.Test/YearMonthDayCalendarTest.cs
src/NodaTime.Test/YearMonthDayTest.cs
src/NodaTime/YearMonthDay.cs
src/NodaTime/YearMonthDayCalendar.cs

We now support months in the range [1, 32]. This is
necessary for the Wondrous calendar which has 19 months.
I've taken the extra bit from the calendar range, so we can now "only"
support 64 calendars... but we've only got 18 at the moment, and the
Wondrous calendar will be the 19th. I think that's safe.
This needs to be done before 2.0 as it affects the serialization
format.
// cc @glittle

Increase the number of bits available to months

---

build/updatehistorictzdb.sh

This only tackles 1.3. I think it's going to be easiest to
have one of these scripts per minor release, and then one
to call them all (moving some of this script there).
It doesn't rebuild any documentation, so the docs will still show
(e.g.) 1.3.2... but I think that's okay.
I've used this to build a 1.3.3, but I won't push that just yet - I
want to make the web site automatically detect the new release too,
before I do that.
Fixes #360.

First pass at an "update TZDB" script

---

src/NodaTime/AnnualDate.cs
src/NodaTime/BinaryFormattingConstants.cs
src/NodaTime/LocalDate.cs
src/NodaTime/YearMonthDay.cs
src/NodaTime/YearMonthDayCalendar.cs

This now hides the raw value format, which is nice.
Serialization will take up a bit more space, but be more flexible
to later implementation changes.
Fixes #679.

Change serialization format of year/month/day/calendar

---

src/NodaTime/Text/OffsetDateTimePatternParser.cs
src/NodaTime/Text/ZonedDateTimePatternParser.cs

We used to split the template values for OffsetDateTime and ZonedDateTime because extracting the date and time parts was expensive.
In 2.x it's dirt cheap, so let's keep the code cleaner.

Remove a 1.x optimization

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.Serialization.JsonNet/NodaTime.Serialization.JsonNet.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime.TzValidate.NodaDump/NodaTime.TzValidate.NodaDump.csproj
src/NodaTime.TzValidate.NzdCompatibility/NodaTime.TzValidate.NzdCompatibility.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime/NodaTime.csproj

We basically rely on NETStandard.Library 1.6.1 as an atomic dependency unit.
See http://stackoverflow.com/questions/42946951 for background and great answers
Fixes #695.

Remove explicit dependencies where possible

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.NzdPrinter/NodaTime.NzdPrinter.csproj
src/NodaTime.Serialization.JsonNet/NodaTime.Serialization.JsonNet.csproj
src/NodaTime.Serialization.Test/NodaTime.Serialization.Test.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime.TzValidate.NodaDump/NodaTime.TzValidate.NodaDump.csproj
src/NodaTime.TzValidate.NzdCompatibility/NodaTime.TzValidate.NzdCompatibility.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime/NodaTime.csproj

This appears to be the default now anyway, but it's possible that
it's a weaker version, or not the default everywhere. No harm in
being explicit.
Fixes #359.

Explicitly request deterministic builds

---

build/buildrelease.sh

This is a workaround for #713. It's not great, but hopefully it's
good enough for now.

Build dependencies correctly with version suffix

---

src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/ZoneYearOffsetTest.cs
src/NodaTime/TimeZones/ZoneYearOffset.cs

Previously, we were following zic: if a rule says "exactly Feb 29th"
or "at least Feb 29th" it was invalid in a non-leap year. This is
painful due to the way we ask rules for transitions; it's simpler to
ignore the rule, and just treat Feb 29th as Feb 28th in non-leap
years.
It shouldn't make any different to validly-defined rules in TZDB,
although it does make us more lenient with badly-defined fules.
Importantly, it allows us to handle some valid BCL rules.
Fixes #743.

"Handle" Feb 29th rules more cleanly

---

.gitignore
src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime.Test/Text/LocalDateTimePatternTest.cs

Remove filtering of tests which used to be excluded on Mono due to Mono bugs, but where it now works (with 4.8.0 at least).

Run more tests on Mono

---

src/NodaTime.Test/Text/Cultures.cs
src/NodaTime.Test/Text/LocalTimePatternTest.cs

Passes on Mono on both Linux and Windows.

More Mono-specific test ignoring (missed before)

---

build/clonedocfx.sh
src/NodaTime.Web/Markdown/developer/index.json
src/NodaTime.Web/Markdown/developer/website.md

Add a new page in the developer guide documenting how the nodatime.org website works, and include a script that can be used to quickly repopulate the docfx/ directory from the production content, for local development.

Document how to build and run the website app

---

src/NodaTime/Extensions/IsoDayOfWeekExtensions.cs

We have to live with this until 3.0 now, of course... but at least
we can make the badly-named method obsolete.
Fixes #776.

"Rename" ToIsoDayOfWeek(IsoDayOfWeek) to ToDayOfWeek(IsoDayOfWeek)

---

src/NodaTime/Text/ParseResult.cs

Expose those methods to conveniently be able to extend ParseResult with recovery and monadic operations/LINQ, based on discussion in #780
This isn't the absolute minimum exposed set to do things as a consumer; Convert and ConvertError can be reimplemented with just ForValue and ForException, but it is somewhat convenient to expose them, and I do believe generally useful. If you prefer not to expose those members, I'd be really happy with a variant with just the factory methods too.

expose factory methods and conversions

---

build/docfx/template/partials/scripts.tmpl.partial

Add the Google Analytics tracking code to the API documentation, by overriding the default DocFX `partials/scripts` template.

Add the Google Analytics tracking code to the API documentation.

---

src/NodaTime.Web/Views/Shared/_Layout.cshtml

Place the current (1.3.x and 2.0.x) versions at the top of the API/User Guide menu options, and rename "Unstable" to "Development" (in the menu label only).
Also remove the dividers, which don't seem to be adding much.

Highlight the 1.3.x and 2.0.x versions of the API and User Guide.

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime/Duration.cs
src/NodaTime/Fields/TimePeriodField.cs
src/NodaTime/Period.cs

The approach taken before was fundamentally unsound. It's clearer to
consider that when we get down to time-based fields, they're all
fixed-length, so we only need to consider the duration between the
start and end points. This is an initial fix to patch into 2.0.2 -
it's not as efficient as it might be, but it's reasonably minimal.
Further refactoring will come in a separate PR, but that can stay on
the master branch only.
Fixes #824.

Fix Period computation bug

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime/Period.cs

- Use long arithmetic more widely, only using Duration arithmetic
where absolutely necessary (big performance boost)
- Use DivRem where available
- Remove TODO comments after testing

Further tidy-ups of Period

---

src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs
src/NodaTime.Test/DurationTest.Construction.cs
src/NodaTime/Duration.cs

- For most units, we can stick entirely in Int64 arithmetic, so do that
- More test cases (expressed more cleanly)
- Fix a typo in DurationBenchmark
Fixes #837.
Benchmark results (on netcoreapp1.1, just the affected tests):
Before:
```
|                           Method |        Mean |    StdErr |     StdDev |      Median |
|--------------------------------- |------------ |---------- |----------- |------------ |
|                   FromHours_Tiny |  25.7766 ns | 0.2758 ns |  1.3510 ns |  25.3726 ns |
|                 FromMinutes_Tiny |  27.1239 ns | 0.2874 ns |  1.9280 ns |  26.5030 ns |
|                 FromSeconds_Tiny |  27.3131 ns | 0.2909 ns |  2.3456 ns |  26.4874 ns |
|            FromMilliseconds_Tiny |  25.8455 ns | 0.2895 ns |  1.0832 ns |  25.7541 ns |
| …
```

Optimize Duration.From* integer methods

---

.travis.yml
build/appveyor.sh
build/coverage.sh

In AppVeyor we can build all of NodaTime-All.sln
In Travis it's harder, as building the solution will fail due to the
desktop frameworks not being available.

Build more projects in CI

---

src/NodaTime/Duration.cs
src/NodaTime/Fields/TimePeriodField.cs

Fixes #838 
(I've managed to delete the benchmark comparisons I had, but they were fairly significant - particularly avoiding using BigInteger on the way to double. When we've got benchmarks on the website I can edit this PR comment to link to an appropriate comparison :)

Duration optimizations

---

src/NodaTime.Serialization.Test/NodaTime.Serialization.Test.csproj
src/NodaTime.Test/Calendars/CopticCalendarSystemTest.cs
src/NodaTime.Test/DateTimeZoneProvidersTest.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime.Testing/FakeClock.cs
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime/CalendarSystem.cs
src/NodaTime/ClockExtensions.cs
src/NodaTime/Duration.cs
src/NodaTime/Instant.cs
src/NodaTime/LocalTime.cs
src/NodaTime/NodaConstants.cs
src/NodaTime/NodaTime.csproj
src/NodaTime/Period.cs
src/NodaTime/Text/DurationPattern.cs
src/NodaTime/Text/InstantPattern.cs
src/NodaTime/Text/LocalDatePattern.cs
src/NodaTime/Text/LocalDateTimePattern.cs
src/NodaTime/Text/LocalTimePattern.cs
src/NodaTime/Text/OffsetDateTimePattern.cs
src/NodaTime/Text/OffsetPattern.cs
src/NodaTime/Text/PeriodPattern.cs
src/NodaTime/Text/ZonedDateTimePattern.cs

(Sorry, this is what happens when I have a flight :)
I'd suggest reviewing one commit at a time. When I've worked out the exact order in which to change things, I'll build a 1.4.x doc set, and then the change from 1.4.x to 2.0.x should show that most of the members deleted in 2.0.x were obsolete in 1.4.x.

More 1.4 to 2.0 compatibility

---

build/buildhistory.sh
build/docfx/docfx-1.4.x.json

We weren't stopping on errors, which hid two problems:
- Fetching the serialization repo with depth 1 didn't fetch the tag
we need.
- We didn't have a 1.4 docfx.json

Fix buildhistory.sh

---

src/NodaTime.Testing/FakeClock.cs
src/NodaTime.Testing/TimeZones/FakeDateTimeZoneSource.cs
src/NodaTime.Testing/TimeZones/MultiTransitionDateTimeZone.cs
src/NodaTime.Testing/TimeZones/SingleTransitionDateTimeZone.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/DateTimeZone.cs
src/NodaTime/Duration.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs
src/NodaTime/NodaTime.csproj
src/NodaTime/OffsetDateTime.cs
src/NodaTime/SystemClock.cs
src/NodaTime/Text/InstantPattern.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/TimeZones/BclDateTimeZoneSource.cs
src/NodaTime/TimeZones/CachedDateTimeZone.cs
src/NodaTime/TimeZones/DateTimeZoneSourceExtensions.cs
src/NodaTime/TimeZones/DaylightSavingsDateTimeZone.cs
src/NodaTime/TimeZones/FixedDateTimeZone.cs
src/NodaTime/TimeZones/IDateTimeZoneSource.cs
src/NodaTime/TimeZones/PrecalculatedDateTimeZone.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs
src/NodaTime/ZonedClock.cs
src/NodaTime/ZonedDateTime.cs

If I've got this right, this (with #875) should complete the 1.4 work, I think...
We're left with the following which have been removed in 2.0 but can't be made obsolete in 1.4:
- The `IsoDayOfWeek` property in various types, which has been renamed to `DayOfWeek` in 2.0, but there's already a `DayOfWeek` property of type `int`
- Overriding `Equals/GetHashCode` from `object` in `DateTimeZone`
- The `ZoneInterval` constructor, which will be source compatible as it now takes `Instant?` values instead of `Instant` (with a slight wrinkle that `Instant.MinValue` and` Instant.MaxValue` are now "regular" extreme values rather than sentinel values for "beginning and end of time"
Each commit is self-contained - I'd suggest reviewing one commit at a time.

Remaining 1.4 obsolete attributes

---

src/NodaTime.Test/Calendars/BclCalendars.cs
src/NodaTime.Test/Calendars/SimpleWeekYearRuleTest.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime/CalendarSystem.cs
src/NodaTime/Calendars/IWeekYearRule.cs
src/NodaTime/Calendars/SimpleWeekYearRule.cs
src/NodaTime/Calendars/WeekYearRules.cs
src/NodaTime/NodaTime.csproj

This will allow us to make GetGregorian(int) etc obsolete while
providing 2.0.x-compatible alternatives.
The implementation and tests are as close to 2.0.x as I could make
them - they're not necessarily how I'd normally write them with 1.x,
but I wanted to make as few changes as possible. (Hence the multiple
conversions between ticks and days, because 2.0 is day-based.)
(I'm not sure if there's an easy way of comparing this code with the 2.0 equivalent other than downloading it...)

Added IWeekYearRule to 1.4.x.

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Demo/LocalDateTimeDemo.cs
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.NzdPrinter/NodaTime.NzdPrinter.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime.TzValidate.NodaDump/NodaTime.TzValidate.NodaDump.csproj
src/NodaTime.TzValidate.NzdCompatibility/NodaTime.TzValidate.NzdCompatibility.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime/NodaTime.csproj

(Will merge on green; no need for separate review.)
Simplify or fix project files
- We don't need to state the package ID or assembly name; it's implicit in the directory structure
- We don't need to generate runtime configuration for Exe-targeting projects
- The RepositoryUrl shouldn't have the .git part
- We don't need PackageTargetFallback any more
- NzdPrinter can support netcoreapp1.0
- The NodaTime.Testing package should have a RepositoryUrl

Simplify projects

---

src/NodaTime.Test/DurationTest.cs
src/NodaTime.Test/LocalDateTest.Comparison.cs
src/NodaTime.Test/LocalDateTimeTest.cs
src/NodaTime.Test/LocalTimeTest.cs
src/NodaTime/Duration.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs

- Duration
- LocalDate
- LocalDateTime
- LocalTime
These join Offset and Instant that already have the same methods.
OffsetDateTime and ZonedDateTime don't have these as they make less
sense; this mirrors which types have `<` and `>` operators.
Fixes #900.

Provide Min/Max for all suitable types

---

src/NodaTime/Instant.cs

Instead of changing the ticks to nanoseconds, I've removed the
implementation-specific part of the documentation. The fact that the
internal representation uses the Unix epoch is now hidden as far as
possible - anything relying on the Unix epoch is very explicit in
the name.
(I've checked through Instant for all occurrences of "tick" and it seems okay.)
Fixes #922.

Fix Instant documentation

---

build/autobuildweb.sh
build/buildweb.sh
src/NodaTime.Web/Program.cs
src/NodaTime.Web/Startup.cs
src/NodaTime.Web/appsettings.smoketests.json

I will schedule autobuildweb.sh to be run once every half hour
(excluding the benchmark period if I can). With the smoke tests as
part of the buildweb.sh script, we can be reasonably confident that
this won't break the site...
Fixes #916

Introduce smoke tests and web site autobuild script

---

build/buildweb.sh

Sometimes moving fails spuriously - this should be more reliable
(though more time-consuming).

Copy the docfx directory instead of moving it

---

build/travis.sh

(Also, don't manually build the tests before running them. We were
doing so inconsistently anyway, and the important point is to build
NodaTime first so we see any issues there early.)

Run release builds on Travis

---

src/NodaTime.Benchmarks/NodaTimeTests/TimeZones/StandardDaylightAlternatingMapBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/TimeZones/ZoneRecurrenceBenchmarks.cs

These were suggested by some diagnostic work investigating where .NET Core is slower on Linux than Windows.

Add time zone benchmarks

---

src/NodaTime.Benchmarks/NodaTimeTests/LocalDateTimeBenchmarks.cs

This has to return a wrapper as LocalInstant is internal.

Add benchmark for LocalDateTime.ToLocalInstant

---

build/runbenchmarks.sh

This way we don't clone a repo for no reason.
Fixes #917.

Early-out for benchmarking

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

Fixes #686 as far as we intend to.
Previous total test times for netcoreapp:
- Travis: 60.5s
- AppVeyor: 15.7s

Significant optimization of tests for GuessZoneIdByTransitionsUncached

---

src/NodaTime.Test/InstantTest.cs
src/NodaTime.Test/LocalInstantTest.cs
src/NodaTime/Instant.cs
src/NodaTime/LocalInstant.cs

Fixes #957.
(Cherry-picked from master.)

Fix LocalInstant.SafeMinus near start/end of time

---

src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs

This is almost entirely for .NET 4.5 tests, but it makes a huge difference.
Test time before on AppVeyor (doing coverage as well): 183s

Improve test speed significantly

---

src/NodaTime.Test/Text/DurationPatternTest.cs
src/NodaTime.Test/Text/LocalTimePatternTest.cs
src/NodaTime.Test/Text/OffsetDateTimePatternTest.cs
src/NodaTime.Test/Text/ZonedDateTimePatternTest.cs

Locally I see full coverage (as far as possible) for the Text
and Text.Patterns namespace. On AppVeyor it's different, and I'm not
sure why. These should help a bit...

More text tests

---

src/NodaTime.Test/Extensions/ClockExtensionsTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/DateTimeZoneCacheTest.cs
src/NodaTime.Test/TimeZones/TimeZoneInfoReplacer.cs
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/TimeZones/BclDateTimeZoneSource.cs
src/NodaTime/TimeZones/IO/TzdbStreamData.cs
src/NodaTime/TimeZones/TimeZoneInfoInterceptor.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

The important change introduced here is an interceptor for TimeZoneInfo calls.
Is this too heavy-weight given that there aren't many tests that rely on it?
(Many of the tests introduced in this PR *don't* depend on the introduction of the interceptor. Let me know if you'd like me to split them out into separate commits.)
This PR also fixes a bug where if you ask for the system default time zone in an environment where TimeZoneInfo.Local returns null, we blew up with a NullReferenceException instead of a DateTimeZoneNotFoundException. I think it's sufficiently corner-casey that we don't need to patch 2.2.
The remaining uncovered lines are pretty much all for time zone IO. We have the time zone *reading* code in NodaTime.dll, but the *writing* code is all in NodaTime.TzdbCompiler. We could …

More coverage of time zone code

---

src/NodaTime.Test/Text/ZonedDateTimePatternTest.cs
src/NodaTime/Text/ZonedDateTimePatternParser.cs

We were previously stopping too early in the search.
Fixes #981. Should probably be backported to 1.4.x and 2.2.x.
Note for reviewers: would it be worth splitting this into an internal method that could then be tested more thoroughly? I'm pretty confident in it now, but presumably I was confident before, too...

Be more persistent when parsing time zones

---

src/NodaTime/Text/TextErrorMessages.cs

Sample:
Unhandled Exception: NodaTime.Text.InvalidPatternException:
The standard format "H" is not valid for the NodaTime.LocalDateTime
type. If the pattern was intended to be a custom format, escape it
with a percent sign: "%H".
I haven't implemented the "detect whether it's a valid custom
pattern" part - I think that would be a bigger (and slightly
riskier) change without much benefit.
Fixes #971.

Improve error message for invalid standard patterns.

---

src/NodaTime.Test/Text/Cultures.cs

In particular, my local Ubuntu machine uses capitalized day/month
names, causing tests to fail. This normalizes that just for the sake
of tests.
Fixes #943.

Fix text tests on some versions of Linux

---

build/DocfxAnnotationGenerator/Program.cs
build/buildapidocs.sh
build/buildhistory.sh
build/docfx_functions.sh

The change to the annotation generator is due to a new version of
docfx which expects a comment at the start of each yml file (but the
comment isn't preserved by a load/save cycle).
I've got the history branch ready to push just before I merge this PR.
Fixes #938.

Fetch docfx version explicitly

---

src/NodaTime.Web/Models/TzdbDownload.cs
src/NodaTime.Web/Program.cs

I have a slight concern that this may trigger clients to get
confused, thinking that something's changed but then being surprised
when nothing has.
One option would be to use http for anything at or prior to 2017c,
but https from 2017d onwards.
Fixes #999. (I believe this is all there is left.)

Update TZDB downloads to https

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime/LocalDate.cs
src/NodaTime/Period.cs

Ok, trying to address #299.
I've just edited the xml documentation for the `Between` method in `Period` and for the "-" operator in `LocalDate`, and also added a small unit test asserting that the exception is being thrown.

Document exception behavior for Period

---

build/DocfxAnnotationGenerator/ReflectionMember.cs

At some point we *may* want to automatically append something in the
parameter doc (to say that it won't be null on return) but that's
pretty low priority.
Fixes #1019.

Don't add exception docs for NotNull out parameters

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime.Test/IntervalTest.cs
src/NodaTime.Test/LocalDateTimeTest.cs
src/NodaTime.Test/LocalTimeTest.cs
src/NodaTime.Test/OffsetDateTest.cs
src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/OffsetTimeTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/DateInterval.cs
src/NodaTime/Interval.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs
src/NodaTime/OffsetDate.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs
src/NodaTime/ZonedDateTime.cs

As discussed in #585.
I didn't implement the non-nullable overload on `Interval`, though. It seems the compiler isn't able to disambiguate between the two overloads when I try to use the deconstruction syntax.

Add Deconstruct method to selected types

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

First try at adressing #1037.
Implemented `Contains`, `Intersects`, `Intersection`, but haven't implemented `Union` yet.

Add set operations to DateInterval type

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

The optimization checking for "this" in contains is unlikely to be
significant even when the values are equal, and hurt slightly
otherwise - removed for now.

Minor tweaks for DateInterval

---

src/NodaTime.Test/Calendars/WondrousCalendarSystemTest.cs
src/NodaTime/Calendars/WondrousYearMonthDayCalculator.cs

- Remove WondrousYearInfo: we never need both parts together,
so just use two separate methods instead.
- Remove the cache: a dictionary is going to be more involved
than the simple array lookup anyway, and it's not thread-safe.
- Simplify CalculateStartOfYearDays - aside from anything else,
now we don't need to use DateTime :)
- Change WondrousYearMonthDayCalculator to *only* use the
"Ayyam-i-Ha are part of month 18" model, e.g. for GetDaysInMonth.
The alternative model of "Ayyam-i-Ha are in month 0" is used
extensively in WondrousCalendarSystemTest. Fixes #1044.
@glittle Please could you review? It's nice to see that the calculator is now only 276 lines :)

Tweaks to the Wondrous calendar system

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs

- Old ignored tests can now be used again
- Namibia fails, as its rules changed relatively recently

Update time zone tests

---

src/NodaTime.Web/Markdown/1.0.x/concepts.md
src/NodaTime.Web/Markdown/1.3.x/concepts.md
src/NodaTime.Web/Markdown/2.0.x/concepts.md

While browsing the (excellent!) [core concepts docs](https://nodatime.org/2.2.x/userguide/concepts), I saw the following:
> ![image](https://user-images.githubusercontent.com/2148318/36069844-a0717d00-0ebe-11e8-9a56-4f1ddb3a4376.png)
It appears that the bullet points started unintentionally early due to the formatting.
I adjusted the formatting to remove the first bullet point (replacing it with a comma), and adding spacing between the other bullet points. I did this for all instances of this particular issue across the `1.0.x`, `1.3.x`, and `2.0.x` branches.

Fix markdown bullet formatting within core concepts page

---

src/NodaTime.Web/Views/Shared/_Layout.cshtml

Fixes a reported issue around using "More Info" from a user guide or API page

Make the more info link absolute

---

src/NodaTime.Test/Calendars/BadiCalendarSystemTest.cs
src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime/CalendarOrdinal.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/Calendars/BadiYearMonthDayCalculator.cs
src/NodaTime/Calendars/Era.cs

I've confirmed that the most proper name for the calendar is a transliteration of the Arabic name Badíʿ (meaning "wondrous" or "unique"). I'd been using the name "Wondrous" but the preferred use in English is Badíʿ.  In code, I've dropped the accent from the "i" and the "ayin" character.

rename "Wondrous" to "Badi"

---

src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.Web.Test/NodaTime.Web.Test.csproj

These are provided by Visual Studio. I believe they should be
removable in VS15.7, but until then it's simpler to have a single
commit that we can revert later than to let the changes accidentally
end up in other commits.

Automatic project changes

---

src/NodaTime.Web/Views/Home/Docs.cshtml
src/NodaTime.Web/bundleconfig.json
src/NodaTime.Web/wwwroot/css/site.css

- Remove another redundant section class=body (see source of
https://nodatime.org/versions for an example)
- Change the text colour for section headers
- Remove accordian from the minimized js

More web site changes

---

src/NodaTime.Test/TimeZones/BclDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

This was found when trying out C# 8 nullable references.
TimeZoneInfo.Local has been observed to return null in some Mono
installations. We should handle that as reasonably as we can. We
already did for BclDateTimeZoneSource, but now we do in
TzdbDateTimeZoneSource too. Added tests for everywhere we need to
use TimeZoneInfo.Local (via the interceptor).

Fix issues when TimeZoneInfo.Local is null

---

src/NodaTime/TimeZones/DateTimeZoneNotFoundException.cs

This is the first part of addressing #1132; we may still want to
delete it entirely.

Adjust comment for DateTimeZoneNotFoundException

---

src/NodaTime.Test/TestHelper.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime.Tools.DumpTimeZoneInfo/Program.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/Utility/Preconditions.cs

This is mostly just a starting point to see if the test failures go down...
(Fixing #1140)

Fix .NET Core on Unix handling of TimeZoneInfo as far as possible

---

build/runbenchmarks.sh

This is to work around a Linux issue with .NET Core 2.1
https://github.com/dotnet/cli/issues/9397
(So far we haven't seen it hurt the Travis build, which may have it
disabled by default.)

Disable msbuild node reuse when running benchmarks

---

src/NodaTime/OffsetDate.cs

I believe this will give a significant performance improvement on the
full framework, but we need to wait for the benchmarks to be run
automatically before merging.

Use fields instead of properties within OffsetDate

---

src/NodaTime.Web/Markdown/2.0.x/recipes.md

Fixes #1062.
Note that the using directive isn't in the recipe itself, as that
would conflict with other upcoming changes.

Explain InZone in the recipes page

---

build/buildweb.sh
build/finishautobuildweb.sh
src/NodaTime.Web.Blazor/NodaTime.Web.Blazor.csproj
src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime.Web/Startup.cs

We keep the project available to experiment with, but remove it from the deployed site right now.

Remove Blazor from deployed site

---

build/buildweb.sh
src/NodaTime.Web/NodaTime.Web.csproj

I now suspect the problem is with msbuild node reuse rather than the
BuildBundlerMinifier package itself. We'll see...

Another attempt to fix the web build

---

src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs

OffsetDateTime currently uses a single 64-bit integer field for
offset and nano-of-day; we can do the same thing in OffsetTime.
Once this change is in, we can experiment with changing
OffsetDateTime to use OffsetTime instead of its own field, and maybe
use LocalDate instead of its own YearMonthDayCalendar, due to
improvements with readonly structs.

Optimize OffsetTime representation

---

src/NodaTime/Instant.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/OffsetDateTime.cs

This used to affect performance, but that was before readonly
structs etc. The code is definitely simpler using LocalDate.
Next step would be to try to use OffsetTime instead of the long, but
that's more complicated. Let's see what the performance impact of
this is first.

Experimental change to OffsetDateTime

---

src/NodaTime/AmbiguousTimeException.cs
src/NodaTime/AssemblyInfo.cs
src/NodaTime/BinaryFormattingConstants.cs
src/NodaTime/DateTimeZoneProviders.cs
src/NodaTime/Duration.cs
src/NodaTime/Extensions/ClockExtensions.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/IDateTimeZoneProvider.cs
src/NodaTime/Instant.cs
src/NodaTime/Interval.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs
src/NodaTime/NodaTime.csproj
src/NodaTime/Offset.cs
src/NodaTime/OffsetDate.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs
src/NodaTime/Period.cs
src/NodaTime/SkippedTimeException.cs
src/NodaTime/Text/InvalidPatternException.cs
src/NodaTime/Text/UnparsableValueException.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/TimeZones/BclDateTimeZoneSource.cs
src/NodaTime/TimeZones/DateTimeZoneNotFoundException.cs
src/NodaTime/TimeZones/InvalidDateTimeZoneSourceException.cs
src/NodaTime/TimeZones/ZoneYearOffset.cs
src/NodaTime/Utility/InvalidNodaDataException.cs
src/NodaTime/ZonedDateTime.cs

This means the netstandard1.3 and netstandard2.0 builds will do the same thing. (The changes required to make netstandard2.0 work properly with BclDateTimeZone are in the master branch.)

Define a NETSTANDARD constant for all netstandard builds

---

src/NodaTime.Web/Models/GoogleStorageBenchmarkRepository.cs

Not sure how this happened, and it looks like there's only one such
benchmark, but let's not fail to load the rest...
Fixes #1213

Skip benchmarks with no environment

---

src/NodaTime.Web/Markdown/2.0.x/offsetdatetime-patterns.md
src/NodaTime.Web/Markdown/2.0.x/zoneddatetime-patterns.md
src/NodaTime.Web/Markdown/2.1.x/zoneddatetime-patterns.md

For both ZonedDateTime and OffsetDateTime, an embedded LocalDateTime
pattern is specified with `l<...>`, not `ldt<...>`
Fixes #1218.

Fix embedded pattern documentation

---

build/appveyor.sh

(This should fix appveyor, but not Travis, which still doesn't have the .NET Core 3.0 preview bits available.)

Disable code coverage temporarily

---

build/docfx/docfx-unstable.json
build/docfx_functions.sh

(For NodaTime.Serialization.JsonNet we need to specify the target framework, which we don't with any other project now.)
This partially addresses #1245, but doesn't fix it fully.

Update docfx and fix serialization docfx input

---

src/NodaTime.Test/Text/TypeConvertersTest.cs
src/NodaTime/Offset.cs
src/NodaTime/OffsetDate.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs
src/NodaTime/Text/TypeConverters.cs

This PR just builds on the work from @austindrenski in [PR1237](https://github.com/nodatime/nodatime/pull/1237) the goal here is just to have complete coverage on all NodaTime types that have formatter & parser support.

Add TypeConverters for Offset types

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj

net461 doesn't work when the machine has net471 installed, due to
https://github.com/dotnet/standard/issues/567 (which is very
unfortunate).

Update benchmark targets to net471 and netcoreapp3.0

---

src/NodaTime.Web/Views/Downloads/Index.cshtml
src/NodaTime.Web/wwwroot/robots.txt

I suspect that removing benchmarks may well make a significant difference on its own.
Fixes #1266 (at least mostly)

Prevent robots from trawling where we don't want them to

---

appveyor.yml

Note that we don't install the runtime separately, as that's
installed as part of the SDK.

AppVeyor: Install the .NET Core SDK on the fly, and use VS2017 image

---

lib/commandline/CommandLine.cs
src/NodaTime/AnnualDate.cs
src/NodaTime/DateInterval.cs
src/NodaTime/Duration.cs
src/NodaTime/Instant.cs
src/NodaTime/Interval.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalInstant.cs
src/NodaTime/LocalTime.cs
src/NodaTime/Offset.cs
src/NodaTime/OffsetDate.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs
src/NodaTime/Text/ParseResult.cs
src/NodaTime/TimeZones/Transition.cs
src/NodaTime/TimeZones/ZoneInterval.cs
src/NodaTime/TimeZones/ZoneLocalMapping.cs
src/NodaTime/YearMonthDay.cs
src/NodaTime/YearMonthDayCalendar.cs
src/NodaTime/ZonedDateTime.cs

- Equals(object) should accept null
- (Implementation detail) use pattern matching in Equals
- Add documentation for ParseResult.ConvertTo type parameter
- Improve formatting of documentation for ZoneLocalMapping (docfx bug?)
Fixes #1275

Fixes from API review:

---

src/NodaTime.Web/Markdown/1.0.x/localtime-patterns.md
src/NodaTime.Web/Markdown/1.0.x/offset-patterns.md
src/NodaTime.Web/Markdown/1.1.x/localtime-patterns.md
src/NodaTime.Web/Markdown/2.0.x/localtime-patterns.md

Specifically, replace occurrences of `*foo*` with `<em>foo</em>` when it occurs within a table, as HTML elements inhibit Markdown processing.

Fix Markdown use within tables.

---

src/NodaTime.Test/Text/DurationPatternTest.cs
src/NodaTime.Web/Markdown/unstable/duration-patterns.md
src/NodaTime/Text/DurationPattern.cs
src/NodaTime/Text/DurationPatternParser.cs

This matches the pattern that NodaTime.Serialization.JsonNet uses,
which just has a number of hours (and smaller) rather than the days
and hours of the regular roundtrip pattern.
Fixes #1290.
**Reviewers**
Thoughts on the choice of "j" as the standard pattern are welcome, along with the documentation. There's nothing JSON-specific about this format, but it happens to be the reason we're creating it.

Add a new roundtrip pattern for durations

---

build/finishautobuildweb.sh

This should mean it ends up in the GCR image too.

Move commit.txt generation to earlier in web build

---

src/NodaTime.Web/appsettings.json

Unfortunately we still have two log lines per request, but that
would require custom code to fix; let's not worry about it for now.

Reduce the noise in production logging

---

src/NodaTime.Web/Markdown/1.0.x/core-types.md
src/NodaTime.Web/Markdown/2.0.x/core-types.md
src/NodaTime.Web/Markdown/2.3.x/core-types.md

Was reading the docs and saw the phrase (emphasis mine)
> An Instant is a point on **notional a** global time-line
And I believe you may have meant:
> An Instant is a point on **a notional** global time-line
So I figured I'd do a quick PR to suggest it.

Fix for phrasing: "notional global timeline"

---

src/NodaTime.Testing/TimeZones/FakeDateTimeZoneSource.cs
src/NodaTime.Testing/TimeZones/MultiTransitionDateTimeZone.cs
src/NodaTime.Testing/TimeZones/SingleTransitionDateTimeZone.cs

The new way of building documentation doesn't work with cross-project inheritdoc tags (until docfx supports it).

Copy inherited docs in the Testing project

---

data/cldr/windowsZones-35.xml

(It looks like we missed CLDR 34. I don't think there's any benefit
in adding that now though.)

Add Windows time zone mappings from CLDR 35.1

---

src/NodaTime.Test/Text/LocalDateTimePatternTest.cs
src/NodaTime/Text/LocalDateTimePattern.cs
src/NodaTime/Text/LocalDateTimePatternParser.cs

Fixes #1219
Also standardize the comment format in LocalDateTimePattern. (I'll revisit this for the other patterns later...)
PR review notes:
We currently have 's' as 'sorted' and 'general ISO', which has no subsecond units. 'S' feels like a natural extension of that, and is still 'longer sorted' in that shorter strings sort before longer strings... is that a reasonable justification?
Note: documentation changes will be in a PR in the nodatime.org repo - that's one of the downsides of splitting the two out...

Use 'S' as the extended ISO standard pattern specifier

---

src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime/Text/LocalDatePattern.cs
src/NodaTime/Text/LocalDatePatternParser.cs

(These were only introduced very recently.)
When documenting them, I found that LocalDateTime has r and R as well, but with "r" meaning "full round trip including calendar" and "R" meaning "no calendar" so it makes sense to make LocalDate conform too.

Swap the standard patterns for LocalDate r/R

---

src/NodaTime.Test/DateAdjustersTest.cs
src/NodaTime/DateAdjusters.cs

I'm not fixed on the name; we could potentially omit "Period" from the name, and change "Add" to "Addition", or "Adder" etc.
I looked at introducing a similar adjuster for LocalTime, but that
could cause confusion:
```csharp
// If this were valid...
TimeAdjuster adjuster = TimeAdjuster.AddPeriod(Period.FromHours(2));
LocalDateTime start = new LocalDateTime(2019, 5, 4, 23, 0); // 11pm on May 4th
// Expectation: result is 1am on May 5th.
// Reality: result is 1am on May 4th, as the adjuster is only applied to time.
LocalDateTime result = start.With(Adjuster);
```
Fixing that would require a "LocalDateTimeAdjuster" which we don't currently have, and I'm not sure it's worth it.

Introduce a date adjuster to add a period when invoked

---

src/NodaTime.Test/Calendars/EraTest.cs

This was previously implicitly being called by test discovery.

Add test for Era.ToString()

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime.Test/LocalDateTimeTest.cs

After this, I believe every line of uncovered code is either "this can't happen" or a nigh-on-impossible-to-test bit of BclDateTimeZone.

Final improved coverage

---

src/NodaTime.Test/ZonedClockTest.cs
src/NodaTime/ZonedClock.cs

I hope that most uses of ZonedClock won't need them, but they don't do active harm.
Fixes #1362

Provide Zone/Clock/Calendar properties on ZonedClock

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.NzdPrinter/NodaTime.NzdPrinter.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime.Tools.Common/NodaTime.Tools.Common.csproj
src/NodaTime.Tools.DumpTimeZoneInfo/NodaTime.Tools.DumpTimeZoneInfo.csproj
src/NodaTime.Tools.ValidateHistoricalNzd/NodaTime.Tools.ValidateHistoricalNzd.csproj
src/NodaTime.TzValidate.NodaDump/NodaTime.TzValidate.NodaDump.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime/NodaTime.csproj

This is required by recent previews of the .NET Core SDK, but VS still needs the old property. We can go down to just this one when .NET Core 3.0 is released, I suspect.

Use Nullable msbuild property

---

src/NodaTime/NodaTime.csproj

... since it can be used outside the full .NET Framework now.

More general package description

---

src/NodaTime.Demo/DateAdjustersDemo.cs

end-variable wasn't used in the generated snippets so moved it to be inlined instead to tidy up the snippets for all DateAdjusterDemo-tests

Change end-variable from declared variable to inline in DateAdjusterDemo

---

src/NodaTime.Demo/DateIntervalDemo.cs

Adds snippet for `Deconstruct` in `DateInterval`.
`Snippet.For()` doesn't have support for void-methods, so any ideas for how to support that with a new signature for `Snippet.For()` would be appreciated :) I can add that into this PR.

Add snippet for Deconstruct

---

src/NodaTime.Benchmarks/NodaTimeTests/Text/LocalDatePatternBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/Text/LocalTimePatternBenchmarks.cs
src/NodaTime.Test/Text/PatternTestData.cs
src/NodaTime/LocalTime.cs
src/NodaTime/Text/LocalDatePatternParser.cs
src/NodaTime/Text/LocalTimePatternParser.cs

Gets the benefits of #1444, but changing everything else turns out not to be useful.
Will only merge after I've got benchmarks working on Bagpuss again.

Date and time parsing optimization

---

src/NodaTime.Benchmarks/NodaTimeTests/Text/LocalTimePatternBenchmarks.cs
src/NodaTime.Test/Text/LocalTimePatternTest.cs
src/NodaTime/Text/LocalTimePattern.cs

(The property name is chosen to match LocalDateTimePattern.GeneralIso, which also only has second precision.)
I haven't introduced a standard pattern for this yet. There's no particularly obvious choice.

Add GeneralIso pattern to LocalTimePattern

---

src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime/Text/LocalDatePatternParser.cs

Fixes #1408.
Another commit will add documentation, but that needs to be in the nodatime.org repo.

Add standard "month/day" pattern.

---

src/NodaTime/Utility/Preconditions.cs

The reference was missing the `<T>` thus making JetBrains Rider complain that it "cannot resolve symbol CheckNotNull".

Fix CheckNotNull<T> cref

---

global.json

So that people can work with NodaTIme with any .NET Core 3.x SDK, see https://andrewlock.net/exploring-the-new-rollforward-and-allowprerelease-settings-in-global-json/ 
Note that rollForward policies are not (yet) supported by Rider: https://youtrack.jetbrains.com/issue/RIDER-38533

Add rollForward=latestMinor in global.json

---

src/NodaTime.Test/DateTimeZoneProvidersTest.cs
src/NodaTime.Test/Text/TypeConvertersTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/DateTimeZoneProviders.cs
src/NodaTime/Text/TypeConverterSettings.cs
src/NodaTime/Text/TypeConverters.cs
src/NodaTime/Xml/XmlSchemaDefinition.cs
src/NodaTime/Xml/XmlSerializationSettings.cs
src/NodaTime/ZonedDateTime.cs

Fixes #1505.
I've left a deprecated property for DateTimeZoneProviders.Serialization.
While moving to 3.0 means we *can* break anything, we actually
restricted the breaking changes to "removing binary serialization"
(and removing incorrectly named method that's been deprecated since
2.1 was released in 2017).
The ForTypeConverter property is new in 3.0, so doesn't need
deprecation. I'll add it to release notes for any existing beta
users, but it should be okay to move. (I'll release a new beta
shortly after this goes in.)
cc @0xced

Extract conversion settings from DateTimeZoneProviders

---

src/NodaTime.Test/PeriodBuilderTest.cs

This has only shown up with the preview of .NET Core SDK 3.1.300,
which makes me nervous in general... but it's a harmless fix.

Fix nullability error in PeriodBuilderTest

---

src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs

Transitions that would be represented as 24:00 in the IANA time zone database are represented as 23:59:59.999 in the Windows database. It makes sense to correct this as we have the facility to do so; the intent of the data is clearly "one millisecond later" even though that's not what the Windows rule actually says. (I don't think anyone would argue that the transition actually happens when the Windows rule says it does.)
Fixes #1524.

Make BclDateTimeZone behave more reasonably for midnight transitions

---

src/NodaTime/DateTimeZone.cs
src/NodaTime/DateTimeZoneProviders.cs
src/NodaTime/IDateTimeZoneProvider.cs
src/NodaTime/TimeZones/BclDateTimeZoneSource.cs

As originally noted in nodatime/nodatime.org#78, there are a few places that still talk about the (non-)availability of `BclDateTimeZone`. This updates all of them to use the same prose (and also add a `<see cref=""/>` that I assume was omitted before due to conditional compilation).

Update documentation to clarify availability of BclDateTimeZone in 3.0.

---

Directory.Build.props

I'm not sure how they worked before, but using a relative path for a signing file in Directory.Build.props caused the execution-time building of benchmarks to fail.
This fix finds the repository root and uses the key from there instead.

Fix benchmark runs

---

src/NodaTime.Test/ConsistencyTest.cs
src/NodaTime.Test/PeriodTest.cs
src/NodaTime.Test/TimeZones/ZoneIntervalTest.cs
src/NodaTime.Test/YearMonthTest.Comparison.cs
src/NodaTime/Period.cs
src/NodaTime/TimeZones/ZoneInterval.cs
src/NodaTime/YearMonth.cs

Additionally, add a check to ensure we don't miss this again, at
least for anything implementing `IEquatable<T>`
Fixes #1529.

Add equality operators for Period and ZoneInterval

---

src/NodaTime.Demo/XmlSchemaDemo.XmlCodeExporterAssemblyCreator.cs
src/NodaTime.Demo/XmlSchemaDemo.XmlSchemaClassGeneratorAssemblyCreator.cs

Mono is cool about loading system assemblies by just providing a simple name. But .NET Framework on Windows is more strict and needs the full assembly name, including the version, culture and public key token.
Without the full assembly name, exception like this would be thrown:
System.IO.FileNotFoundException : Could not load file or assembly 'System' or one of its dependencies. The system cannot find the file specified.
Note that Mono seems to completely ignore the additional version, culture and public key token information when loading the assemblies. It's even possible to change the version to a non existing version (e.g. 6.6.6.6) and Mono loads the assembly anyway.

Fix XmlSchemaDemo on .NET Framework

---

src/NodaTime/CalendarSystem.cs
src/NodaTime/DateTimeZoneProviders.cs

(This is partly a followup to 5046177, which added some extra paragraphs
about DateTimeZoneProviders.Bcl.)

Clean up some more documentation in preparation for a 3.0 release.

---

src/NodaTime.Test/Text/TypeConvertersTest.cs
src/NodaTime/Text/TypeConverters.cs
src/NodaTime/YearMonth.cs

(Like the other converters, this only handles the ISO calendar system.)
Fixes #1539.

Implement a TypeConverter for YearMonth

---

src/NodaTime/Interval.cs

1fb657c fixed up the documentation for various types' equality/ordering, but accidentally uses "date interval" for both `DateInterval` and `Interval`.

Fix a typo in Interval documentation

---

build/tzdbupdate/update-3.0.sh
build/tzdbupdate/update-all.sh

Note that this will fix the lack of an XML file in the NodaTime.Testing package too. (When there's a new TZDB update.)

Update 3.0.x as part of updating TZDB

---

src/NodaTime.Test/Text/Cultures.cs

The French-Canadian culture appears to have some odd settings by default.

Fix tests when running on Ubuntu 20.04

---

src/NodaTime.Test/YearMonthTest.Misc.cs
src/NodaTime/YearMonth.cs

I've added a new method to the YearMonth structure called 'PlusMonths', which is a shortcut to obtaining a new YearMonth object representing the current one plus a number of months.
Addresses #1536

Create method 'PlusMonths()'

---

src/NodaTime/CalendarSystem.cs

(Only shows up with .NET 5 preview; slightly surprised that's being used on my machine, but let's fix it now...)

Fix nullable reference type issue

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj

It's EOL now, so irrelevant.
Fixes #1568

Remove netcoreapp2.0 benchmarks

---

src/NodaTime.Test/Xml/XmlSchemaTest.XmlSchema.approved.xml
src/NodaTime/Xml/XmlSchemaDefinition.cs

From the validation and documentation perspective, having a simple type or a complex type is equivalent.
The benefit of having all NodaTime CLR types described as complex XML schema types is for external tools such as svcutil which behave better with complex types.
Fixes #1597

Define all XML schema types as complex types with simple content

---

src/NodaTime.Test/Xml/XmlSchemaTest.cs

The XML schema was correct but these new test formally ensure that when serialized as XML, an `Interval` may not have either a `start` or an `end` attribute.

Add XML schema validation tests for Interval without start and/or end

---

src/NodaTime/Calendars/GJYearMonthDayCalculator.cs
src/NodaTime/Calendars/GregorianYearMonthDayCalculator.cs
src/NodaTime/Calendars/IslamicYearMonthDayCalculator.cs

The arrays in GJYearMOnthDayCalculator are only used in the places I've changed - so it's definitely safe. Despite the previous (now deleted) comment, the array index wasn't being used for validation anyway.
Fixes #1595.

Use 1-based indexes for all month arrays in Islamic and Gregorian YearMonthDayCalculators

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime.Test/Text/PeriodPatternTest.Roundtrip.cs
src/NodaTime.Test/Text/TypeConvertersTest.cs
src/NodaTime/Text/PeriodPattern.cs

Fixes #1629
Note that we still allow "P" on its own to be parsed, for backward compatibility. (This came for free, as it happens.)

Format Period.Zero as "P0D" in the roundtrip pattern

---

global.json
src/NodaTime.sln

The SDK version must have major.minor.patch else it doesn't work as expected (i.e. always use the latest available SDK).
- With with following .NET SDKs installed:
2.1.816 [/usr/local/share/dotnet/sdk]
3.1.410 [/usr/local/share/dotnet/sdk]
5.0.301 [/usr/local/share/dotnet/sdk]
6.0.100-preview.4.21255.9 [/usr/local/share/dotnet/sdk]
- With "rollForward": "latestMinor"
- With "version": "3.1" in global.json
❌ `dotnet --version` returns 6.0.100-preview.4.21255.9
- With "version": "3.1.410" in global.json
✅ `dotnet --version` returns 3.1.410
- With "rollForward": "latestMajor" and "allowPrerelease": false,
- With "version": "3.1" in global.json
❌ `dotnet --version` returns 6.0.100-preview.4.21255.9 (works by chance)
- With "version": "3.1.410" in global.json
✅ `dotnet --version` returns …

Fix global.json

---

src/NodaTime/YearMonth.cs

The summary of one of the YearMonth constructors contained an erroneous reference to "Day", presumably because the documentation was copied from [here](https://github.com/nodatime/nodatime/blob/aa49ace02d8a46668033e75e2fec0fbbf935e068/src/NodaTime/LocalDate.cs#L96) and edited when first created.
The change is simply to correct this.

Correct documentation on constructor

---

build/appveyor.sh
build/buildrelease.sh
build/ci.sh
build/tzdbupdate/update-master.sh
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.Test/Calendars/HebrewCalendarSystemTest.cs
src/NodaTime.Test/Calendars/IslamicCalendarSystemTest.cs
src/NodaTime.Test/Calendars/PersianCalendarSystemTest.cs
src/NodaTime.Test/NoSlowTests.runsettings
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/coverageparams.xml
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj

Closes #1625
The NUnit test adapter update is required for the `--filter` switch to work as desired for this use case in `dotnet test`. See https://github.com/nunit/nunit3-vs-adapter/issues/473.

Make slow tests opt-in instead of opt-out 

---

build/Coverage.proj
build/coverage-mac.sh
build/coverage.sh

While working on #1642 I needed to change the [coverageparams.xml](/nodatime/nodatime/blob/master/src/NodaTime.Test/coverageparams.xml) file, and I wanted to verify the change. However, I work mostly on a Mac, and the `coverage.sh` script is dependent on Windows: both because it runs against .NET Framework, and because it runs exe files.
This PR updates the versions of dotCover and ReportGenerator, changes them to run against .NET 5 instead of .NET Framework, removes the dependency on `nuget.exe` in favor of `dotnet restore`, and creates a `coverage-mac.sh` script which will run coverage on a Mac.
I did verify that the `coverage.xml` output file is the same after the change to running against .NET 5 (there are some changes compared to master, but those are caused by the version change), …

Run test coverage on .NET 5 and on Mac

---

src/NodaTime.Test/LocalDateTest.Conversion.cs
src/NodaTime.Test/LocalDateTimeTest.cs
src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/ZonedDateTime.cs

This doesn't change the behavior at all; it just documents it.
This is the first step towards implementing #1635.

Document conversions to BCL types for non-Gregorian calendars

---

src/NodaTime/Text/TextErrorMessages.cs

Fixes #1646
Note that while we don't really "know" what kind of type we're
really parsing, we *could* provide the list of all valid format
specifiers for the given context as part of the exception text, if
we think that would be useful.
cc @djeikyb - in particular I'd be interested in your thoughts about the above possibility.

Be more expansive in the error message for bad format specifiers

---

src/NodaTime.Test/YearMonthTest.Misc.cs
src/NodaTime/Text/YearMonthPattern.cs
src/NodaTime/Text/YearMonthPatternParser.cs
src/NodaTime/YearMonth.cs

Fixes #1670
Unfortunately it's too late to make `yearMonth.ToString(null, null)` yield the same results as `yearMonth.ToString()`, due to compatibility reasons. But the result isn't *too* bad, really.
This will need a documentation update to document the new "G" format once it's merged.

Implement ToString() for YearMonth

---

global.json
src/NodaTime/NodaTime.csproj

Jon,
This addition to the CSPROJ is just to prevent anyone from accidentally adding any code that might make NodaTime incompatible with Blazor Web Assembly.
Feel free to disregard it if you'd like but I'm trying to get the libraries I intend to use in Blazor at least marked with the equivalent safeguard so I don't get stung by an unintended minor change.
Buvy

Add safeguard to prevent non webassembly friendly code

---

src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/TestData/LinuxAdjustmentRuleTestData.txt
src/NodaTime.Test/TestData/README
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.LinuxAdjustmentRules.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Tools.DumpTimeZoneInfo/Program.cs
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime/NodaTime.csproj
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/TimeZones/IZoneIntervalMap.cs
src/NodaTime/TimeZones/PartialZoneIntervalMap.cs
src/NodaTime/TimeZones/StandardDaylightAlternatingMap.cs
src/NodaTime/TimeZones/ZoneInterval.cs

This is along the way to #1635. It's a bit of a shame that we have to go back to multiple targets, but there may well be other things we want to be able to do with .NET 6 as well, over time.

Upgrade targets to include .NET 6

---

src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs

This was surprisingly straightforward in the end.

Fix post-2038 dates .NET 6.0 on Linux in BclDateTimeZone

---

src/NodaTime.Benchmarks/NodaTimeTests/LocalDateBenchmarks.cs
src/NodaTime.Test/Extensions/DateOnlyExtensionsTest.cs
src/NodaTime.Test/LocalDateTest.Conversion.cs
src/NodaTime/Extensions/DateOnlyExtensions.cs
src/NodaTime/LocalDate.cs

First part of #1635. (TimeOnly will be in a separate PR.)

Support for DateOnly in .NET 6.0

---

src/NodaTime/DateTimeZone.cs
src/NodaTime/TimeZones/BclDateTimeZone.cs
src/NodaTime/TimeZones/CachingZoneIntervalMap.cs
src/NodaTime/TimeZones/IZoneIntervalMap.cs
src/NodaTime/TimeZones/PartialZoneIntervalMap.cs
src/NodaTime/TimeZones/PrecalculatedDateTimeZone.cs
src/NodaTime/TimeZones/SingleZoneIntervalMap.cs
src/NodaTime/TimeZones/StandardDaylightAlternatingMap.cs

Instead, make sure we implement MinOffset and MaxOffset everywhere, and just put the properties into IZoneIntervalMap
Additionally, suppress and explain CA2119 for DateTimeZone.

Remove IZoneIntervalMapWithMinMax

---

Directory.Build.props

Changes since 3.0.0:
- Added .NET 6.0 target
- Implemented `DateOnly` and `TimeOnly` conversions to/from
`LocalDate` and `LocalTime`
- Fixed `BclDateTimeZone` support in .NET 6.0 on Unix
- Implemented `ToString` method for `YearMonth`
- Improved error messages for bad format specifiers
- Added `LocalDateTime.MinIsoValue` and `LocalDate.MaxIsoValue`
- Added `Period.Between` overload accepting `YearMonth` values
- Added `YearMonth.PlusMonths` method
- Added `Period.DaysBetween` method (previously internal)
- Various documentation improvements

Release Noda Time version 3.1.0

---

src/NodaTime/Calendars/HebrewScripturalCalculator.cs

I was browsing the source of NodaTime as part of mentoring devs at work and saw this. While I agree that `(2, 4, 6, 10, 13) => 29` would be cleaner than what we have and would be preferred to the current solution I thought it might be nice to at least compress the five cases into a single one.

Cleaned up switch using C# 9.0 or pattern

---

src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs

I need to investigate this in more detail, but it looks like either TimeZoneInfo is representing its final rule incorrectly for Asia/Gaza and Asia/Hebron. For the moment, we'll stop the test in 2036...

Work around TimeZoneInfo suspected bug (test only)

---

src/NodaTime.Test/Text/LocalTimePatternTest.cs
src/NodaTime/Text/LocalTimePattern.cs

These patterns allow for ISO-valid values such as "12:35" or just "12".
The same approach can then be extended to LocalDateTimePattern, although we'll need to consult ISO-8601 carefully to see whether the precision for a "date and time" can legitimately be reduced to "just a date".

Provide more LocalTime ISO formats

---

.github/workflows/release.yaml
build/tzdbupdate/update-3.1.sh

New minor versions still need more work... we'll probably need to revert back to building locally, for now. (Certificate management confuses me... I'm just happy if it works *somehow*!)

Sign NuGet packages created as part of updating TZDB

---

.github/workflows/pull-request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
Directory.Build.targets
build/ci.sh
src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.Demo/XmlSchemaDemo.cs
src/NodaTime.NzdPrinter/NodaTime.NzdPrinter.csproj
src/NodaTime.Test/Annotations/TrustedTest.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/Text/LocalDateTimePatternTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime.Tools.DumpTimeZoneInfo/NodaTime.Tools.DumpTimeZoneInfo.csproj
src/NodaTime.Tools.ValidateHistoricalNzd/NodaTime.Tools.ValidateHistoricalNzd.csproj
src/NodaTime.TzValidate.NodaDump/NodaTime.TzValidate.NodaDump.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime/NodaTime.csproj

We now don't test on .NET Core 3.1 as it's unsupported - but I've reintroduced the .NET 4.7.1 tests to run locally, as that's pretty important. (We could use Windows-based GH-actions at some point too.)

Dependency and platform updates

---

src/NodaTime.Test/DurationTest.Operators.cs
src/NodaTime/Duration.cs

There are already methods for `Duration * long`, `long * Duration`, and `Duration * double` . The one variant missing is `double * Duration`. This PR adds those, along with unit tests.

Add missing double*Duration methods

---

src/NodaTime.Test/DateTimeZoneTest.LocalConversions.cs
src/NodaTime/AmbiguousTimeException.cs
src/NodaTime/SkippedTimeException.cs

Fixes #1761
This could theoretically break someone relying on ParamName actually containing the message - but since that's *clearly* a bug, I'd have hoped folks would at least have reported it at the same time, in which case we'd have fixed it earlier.

fix: Fix the arguments passed up to exception base classes

---

src/NodaTime.Test/Text/ParseResultTest.cs
src/NodaTime.Test/Text/PatternTestData.cs
src/NodaTime.Test/Text/Patterns/SteppedPatternBuilderTest.cs
src/NodaTime.Test/Text/TypeConvertersTest.cs
src/NodaTime.Test/Text/ValueCursorTest.cs
src/NodaTime/Text/ParseResult.cs
src/NodaTime/Text/Patterns/SteppedPatternBuilder.cs
src/NodaTime/Text/UnparsableValueException.cs

Having access to the raw value makes it easier to both log it better, and to hide the value from the original message by replacing it with `*****` on critical systems.

Add unparsed value field to UnparsableValueException

---

data/cldr/windowsZones-44.xml
src/NodaTime.TzdbCompiler/Program.cs

This will become "live" in Noda Time releases when there's a new TZDB release.

Add CLDR v44 Windows time zone mapping

---

src/NodaTime.Test/TypeInitializationTest.cs

This avoids us accidentally making a change which causes a type initialization loop. AssemblyLoadContext makes this pretty cheap and simple.

Add tests for type initialization

---

src/NodaTime.Test/ExceptionConstructorTests.cs
src/NodaTime/Text/UnparsableValueException.cs

This was a breaking change in #1760 that I didn't spot at the time.

Restore previously-removed constructors

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs
src/NodaTime.Test/DurationTest.Construction.cs
src/NodaTime.Test/DurationTest.cs
src/NodaTime/Duration.cs

These are only available for the .NET 8 build (although in source code they're .NET 7+ as that's when Int128 was introduced; this is just in case we introduce a .NET 7 build).
Fixes #1777.
Benchmarks show that the Int128 operations are about the same as BigInteger in the worst cases, and about twice as fast in better cases.

Add Duration.ToInt128Nanoseconds and Duration.FromNanoseconds(Int128)

---

build/ci.sh
src/NodaTime.AotCompatibilityTestApp/NodaTime.AotCompatibilityTestApp.csproj
src/NodaTime.AotCompatibilityTestApp/Program.cs
src/NodaTime.sln
src/NodaTime/NodaTime.csproj

No changes to the main library are required (somewhat surprisingly) - I'm expecting the serialization libraries to be somewhat trickier.
See https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/
Fixes #1779

Validate AOT compatibility with both analyzers and a test app

---

src/NodaTime.Test/PeriodTest.cs

In `PeriodTest.cs`, there are four similar tests which are intended to test different `Period.Between()` overloads:
- [BetweenLocalDates_InvalidUnits](https://github.com/nodatime/nodatime/blob/8c41fe377b8ff8121b2942e749c2a3b81e797e20/src/NodaTime.Test/PeriodTest.cs#L104-L111)
- [BetweenLocalTimes_InvalidUnits](https://github.com/nodatime/nodatime/blob/8c41fe377b8ff8121b2942e749c2a3b81e797e20/src/NodaTime.Test/PeriodTest.cs#L317-L326)
- [BetweenLocalDateTimes_InvalidUnits](https://github.com/nodatime/nodatime/blob/8c41fe377b8ff8121b2942e749c2a3b81e797e20/src/NodaTime.Test/PeriodTest.cs#L310-L315)
- [BetweenYearMonth_InvalidUnits](https://github.com/nodatime/nodatime/blob/8c41fe377b8ff8121b2942e749c2a3b81e797e20/src/NodaTime.Test/PeriodTest.cs#L988-L1000)
However, it turns out that …

`Period.Between()` test should cover `LocalDateTime` overload

---

src/NodaTime.Test/Text/LocalTimePatternTest.cs

Hello, my name is Chris. Towards the end of last year, I contacted Jon to more or less ask for his blessing to work on a [Python port of this library](https://github.com/chrisimcevoy/pyoda-time).
In that context, I noticed while reading `LocalTimePatternTest.cs` that there are a couple of historic `TestCaseSource` collections which have fallen into disuse, i.e. there are no remaining references to them.
- [`DefaultPatternData`](https://github.com/nodatime/nodatime/blob/8c41fe377b8ff8121b2942e749c2a3b81e797e20/src/NodaTime.Test/Text/LocalTimePatternTest.cs#L153-L164)
- [`TemplateValueData`](https://github.com/nodatime/nodatime/blob/8c41fe377b8ff8121b2942e749c2a3b81e797e20/src/NodaTime.Test/Text/LocalTimePatternTest.cs#L166-L183)
The last reference to `DefaultPatternData` was [removed in …

Tidy up unreferenced test case source collections in `LocalTimePatternTest.cs`

---

src/NodaTime/Text/AnnualDatePattern.cs
src/NodaTime/Text/DurationPattern.cs
src/NodaTime/Text/LocalDatePattern.cs
src/NodaTime/Text/LocalTimePattern.cs
src/NodaTime/Text/OffsetPattern.cs
src/NodaTime/Text/YearMonthPattern.cs

Fixes #1804.
Equivalent to #1805, but on the 3.1.x branch.

Remove nonsensical aspect of capture for invariant methods.

---

src/NodaTime.Benchmarks/NodaTimeTests/LocalDateBenchmarks.cs
src/NodaTime.Test/LocalDateTest.Conversion.cs
src/NodaTime/LocalDate.cs

If the LocalDate.WithCalendar is called with the same calendar the cost of the DaysSinceEpoch math can be avoided.
BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3880/23H2/2023Update/SunValley3) 12th Gen Intel Core i7-1270P, 1 CPU, 16 logical and 12 physical cores .NET SDK 8.0.303
[Host]     : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2
DefaultJob : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2
| Method                          | Mean     | Error     | StdDev    | Ratio |
|-------------------------------- |---------:|----------:|----------:|------:|
| WithCalendar_Unchanged_New      | 1.045 ns | 0.0150 ns | 0.0133 ns |  0.15 |
| WithCalendar_Unchanged_Previous | 7.043 ns | 0.0941 ns | 0.0880 ns |  1.00 |

Improve perf of LocalDate.WithCalendar if calendar is unchanged

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime/AnnualDate.cs
src/NodaTime/DateInterval.cs
src/NodaTime/Duration.cs
src/NodaTime/Instant.cs
src/NodaTime/Interval.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs
src/NodaTime/Offset.cs
src/NodaTime/OffsetDate.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs
src/NodaTime/Period.cs
src/NodaTime/TimeZones/ZoneInterval.cs
src/NodaTime/YearMonth.cs
src/NodaTime/YearMonthDay.cs
src/NodaTime/ZonedDateTime.cs

Resolves https://github.com/nodatime/nodatime/issues/1693.
Choices made / possible discussion points:
- Ignored `internal` types.
- Added only a test for the `Period` unary negation operator, as that one actually has some implementation.
- Did not implement `IMultiplicativeIdentity`
- `Duration` and `Period` are the most likely candidates to implement it as suggested [here](https://github.com/nodatime/nodatime/issues/1693#issue-1299781520), however I don't think there is a logical multiplicative identity for either of those (1 tick / 1 second / 1 hour / ....).
- Did not implement `IMinMaxValue` for `Period` as I could not figure out a logical `MaxValue`.
- Did not implement `IMinMaxValue` for `LocalDate` and `LocalDateTime`, as they both have `MinIsoValue` and `MaxIsoValue` already and …

Added generic math support.

---

Directory.Build.props

Changes since 3.1.0
- Various minor docs/examples fixes
- More LocalDateTime ISO patterns with reduced precision (
- More LocalTime ISO formats
- Support for configurable "2 digit year max value" in patterns
- Fixed arguments passed to base constructors in AmbiguousTimeException and SkippedTimeException
- Add the unparsed value (and index) to UnparsableValueException
- Made previous UnparsableValueException constructors obsolete
- Optimizations for text handling
- Added .NET 8 target
- Added Instant.ToUnixTimeSecondsAndNanoseconds
- Added Duration.ToInt128Nanoseconds and Duration.FromNanoseconds(Int128) (.NET 8 only)
- Conditionalized the dependency on System.Runtime.CompilerServices.Unsafe
- Added Period.MinValue and Period.MaxValue
- Added generic math support (.NET 8 only)
- Added …

Release Noda Time 3.2.0

---

src/NodaTime.TzdbCompiler.Test/Tzdb/NameIdMappingSupportTest.cs
src/NodaTime.TzdbCompiler/Tzdb/NameIdMappingSupport.cs

(This will only affect users of Noda Time 1.x - hopefully there aren't many of those left now...)

Add hard-coded mapping for Turkey time zone standard name on Windows

---

src/NodaTime.Test/SystemClockTest.cs

Hello again. I noticed this started failing, so I nudged the Instants on by 5 years.
(Should the year in `minimumExpected` and `maximumExpected` be dynamic to prevent this?)
Related to:
- https://github.com/nodatime/nodatime/pull/1465

Update SystemClock test to account for time passing again.

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj

For some reason this causes a failure for Int128-based benchmarks under .NET 8.0. The details aren't clear, and I can't reproduce the problem outside Benchmark.NET, but this fixes the issue.
Fixes #1853

Remove NodaTime.Testing dependency from benchmarks
