src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

Also implement `GetHashCode()` and a basic `ToString()`.
Fixes #380.

Implement IEquatable for DateInterval.

---

build/ReportParameterConsistency/App.config
build/ReportParameterConsistency/Program.cs
build/ReportParameterConsistency/Properties/AssemblyInfo.cs
build/ReportParameterConsistency/ReportParameterConsistency.csproj
build/Tools.sln

Need to put look over this with someone to see where we might use it, but it *did* show the corrected calendarSystem/calendar usage.
This could also detect methods which are overriding base class methods and changing the parameter name...

First pass at a parameter consistency report

---

src/NodaTime.Test/AnnualDateTest.cs
src/NodaTime.Test/DurationTest.cs
src/NodaTime.Test/InstantTest.Operators.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/TestHelper.cs
src/NodaTime/AnnualDate.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalTime.cs
src/NodaTime/NodaTime.csproj

(Looks a bit simple at the moment... not sure what else is needed.)

First pass at an ISO-only annual date type.

---

src/NodaTime.Demo/InstantDemo.cs
src/NodaTime.Serialization.Test/JsonNet/ExtensionsTest.cs
src/NodaTime.Test/Calendars/IsoCalendarSystemTest.cs
src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime.Test/DateTimeZoneTest.GetZoneIntervals.cs
src/NodaTime.Test/InstantTest.Operators.cs
src/NodaTime.Test/InstantTest.cs
src/NodaTime.Test/IntervalTest.cs
src/NodaTime.Test/LocalDateTest.Comparison.cs
src/NodaTime.Test/SystemClockTest.cs
src/NodaTime.Test/Testing/FakeClockTest.cs
src/NodaTime.Test/Testing/TimeZones/MultiTransitionDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/AlgiersTest.cs
src/NodaTime.Test/TimeZones/IO/ReadWriteTest.cs
src/NodaTime.Test/TimeZones/PrecalculatedDateTimeZoneTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/Instant.cs
src/NodaTime/NodaConstants.cs
src/NodaTime/TimeZones/IO/DateTimeZoneReader.cs
src/NodaTime/TimeZones/IO/DateTimeZoneWriter.cs
src/NodaTime/Utility/TickArithmetic.cs
www/unstable/userguide/migration-to-2.md
www/unstable/userguide/versions.md

This fixes issue #371.
// cc @mj1856

Changes to epoch-related members

---

src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/ZonedDateTime.cs

(Will self-review - creating the PR to check CI...)

Reordering of a few methods, and a couple of test fixes.

---

www/_plugins/userguide.rb

It's not clear which plugin has changed, but this wasn't doing what we want.
Given how long it took me to fix this, we should consider changing architecture... a single .NET web app might make sense.

Fix the Jekyll build

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs

I hate just ignoring test failures, but in this case it makes sense to do so.

Ignore test failure described in issue #440

---

src/NodaTime.Test/DurationTest.Construction.cs
src/NodaTime.Test/DurationTest.Operators.cs
src/NodaTime.Test/DurationTest.cs
src/NodaTime/Duration.cs
src/NodaTime/Utility/Preconditions.cs

This builds on PR #453 - it should be a single commit once that's in.

First part of supporting double in the Duration API

---

src/NodaTime.Test/DurationTest.Construction.cs
src/NodaTime.Test/DurationTest.Operators.cs
src/NodaTime/Duration.cs
src/NodaTime/Utility/Preconditions.cs

Implement Duration division by double or another Duration

---

data/cldr/windowsZones-29.xml

The NZD files have not been rebuilt.

Add CLDR v29 Windows mapping data

---

src/NodaTime/Instant.cs

(I knew there was something this would massively simplify...)

Simplify Instant.FromJulianDate using new Duration code for doubles

---

src/NodaTime.Test/Text/LocalDatePatternTest.cs

Just to check that the new comment is rather more reasonable than the old one :)

Clarify year-of-era issue in test comment

---

src/NodaTime.TzValidate.NodaDump/Options.cs
src/NodaTime.TzValidate.NodaDump/Program.cs

Add an output file option.

---

www/unstable/userguide/calendars.md
www/unstable/userguide/weekyears.md

Add detailed week-year documentation

---

.travis.yml

Specify environment in Travis

---

.travis.yml

Suspect this won't help... haven't seen this travis failure before.

Fix travis (maybe)

---

.gitignore

(Also remove comments which look like they'd break the ignore file)

Add CodeRush to gitignore

---

build/SummarizeBenchmarks/Benchmark.cs
build/SummarizeBenchmarks/Program.cs
build/SummarizeBenchmarks/Properties/AssemblyInfo.cs
build/SummarizeBenchmarks/SummarizeBenchmarks.xproj
build/SummarizeBenchmarks/project.json
build/Tools.sln

(This will be replaced when we store the benchmarks elsewhere...)

Initial quick-and-dirty tool to allow us to compare benchmark results

---

src/NodaTime.Demo/StackOverflowExamples.cs
src/NodaTime.Test/Annotations/TrustedTest.cs
src/NodaTime.Test/Text/PatternTestData.cs
src/NodaTime.TzdbCompiler/Program.cs
src/NodaTime.TzdbCompiler/Tzdb/TzdbDatabase.cs
src/NodaTime/TimeZones/FixedDateTimeZone.cs

(Discovered while looking for examples for C# in Depth)

Use more C# 6 features

---

build/appveyor.sh

(Looked like it was green when I merged before. Weird.)

Fix AppVeyor

---

docs/userguide/1.0.x/localtime-patterns.md
docs/userguide/1.1.x/localtime-patterns.md
docs/userguide/1.2.x/localtime-patterns.md
docs/userguide/1.3.x/localtime-patterns.md
docs/userguide/unstable/localtime-patterns.md
www/1.0.x/userguide/localtime-patterns.md
www/1.1.x/userguide/localtime-patterns.md
www/1.2.x/userguide/localtime-patterns.md
www/1.3.x/userguide/localtime-patterns.md
www/unstable/userguide/localtime-patterns.md

Fix LocalTime documentation

---

src/NodaTime.Test/Text/LocalDateTimePatternTest.cs
src/NodaTime.Web/Markdown/unstable/localdatetime-patterns.md
src/NodaTime/Text/LocalDateTimePattern.cs
src/NodaTime/Text/LocalDateTimePatternParser.cs

Document 7-digit precision on LocalDateTime BCL round-trip pattern

---

src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/InstantBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateTimeBenchmarks.cs
src/NodaTime.Test/DurationTest.cs
src/NodaTime.Test/NodaConstantsTest.cs
src/NodaTime.Test/Utility/TickArithmeticTest.cs
src/NodaTime/Duration.cs
src/NodaTime/Instant.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/NodaConstants.cs
src/NodaTime/Utility/TickArithmetic.cs

These are the optimizations I'd been considering earlier. I've tested them, and the differences are not huge, but they're not insignificant either.
Fixes #567.

A few optimizations

---

src/NodaTime.Test/DurationTest.cs
src/NodaTime.Test/InstantTest.cs
src/NodaTime.Test/IntervalTest.cs
src/NodaTime.Test/LocalTimeTest.cs
src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/PeriodTest.cs
src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime.Web/Markdown/unstable/migration-to-2.md
src/NodaTime.Web/Markdown/unstable/versions.md
src/NodaTime/Calendars/GJYearMonthDayCalculator.cs
src/NodaTime/Calendars/IslamicYearMonthDayCalculator.cs
src/NodaTime/Calendars/PersianYearMonthDayCalculator.cs
src/NodaTime/Calendars/RegularYearMonthDayCalculator.cs
src/NodaTime/Calendars/SimpleWeekYearRule.cs
src/NodaTime/Calendars/YearMonthDayCalculator.cs
src/NodaTime/Duration.cs
src/NodaTime/Instant.cs
src/NodaTime/Interval.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/Period.cs
src/NodaTime/Text/FormatHelper.cs
src/NodaTime/Text/LocalDatePatternParser.cs
src/NodaTime/Text/Patterns/DatePatternHelper.cs
src/NodaTime/ZonedDateTime.cs

Quite a few to go, but this is a good start.
I'd suggest reviewing one commit at a time - most commits are trivial.

Fix a lot of TODOs and FIXMEs

---

src/NodaTime.Serialization.JsonNet/DelegatingConverterBase.cs
src/NodaTime.Serialization.Test/JsonNet/DelegatingConverterBaseTest.cs

Fixes #656 (but without unsealing NodaPatternConverter).
See http://stackoverflow.com/questions/42351272 for more context.

Add a delegating converter for JSON

---

src/NodaTime/Calendars/YearMonthDayCalculator.cs
src/NodaTime/Duration.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/LocalTime.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/Period.cs
src/NodaTime/Text/DurationPatternParser.cs
src/NodaTime/Text/ParseResult.cs
src/NodaTime/Text/PeriodPattern.cs
src/NodaTime/Text/ZonedDateTimePattern.cs
src/NodaTime/TimeZones/PartialZoneIntervalMap.cs
src/NodaTime/TimeZones/PrecalculatedDateTimeZone.cs
src/NodaTime/TimeZones/TzdbZone1970Location.cs
src/NodaTime/TimeZones/ZoneInterval.cs
src/NodaTime/Utility/TickArithmetic.cs
src/NodaTime/ZonedDateTime.cs

- feature: We want to consider exposing a feature, but it won't be a breaking change
- optimization: At some point we may want to optimize; usually more benchmarking required first
- tests: More tests required for this area
- misc: Something else :)
A few TODOs aren't covered by this PR as I've already changed them for the next one...
One TODO has been converted into issue #663.

Categorize TODOs (in the NodaTime project) into:

---

src/NodaTime.Web/Markdown/unstable/localdatetime-patterns.md
src/NodaTime.Web/Markdown/unstable/offsetdatetime-patterns.md
src/NodaTime.Web/Markdown/unstable/zoneddatetime-patterns.md

Update patterns documentation to talk about ld, lt and ldt

---

src/NodaTime/Text/DurationPatternParser.cs

I think that the message is fine.

Remove obsolete TODO

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

Make DateInterval always end-inclusive.

---

src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

This is primarily to speed up tests, but it's a safe and useful
optimization anyway.
Fixes #686.

Improve performance of TzdbDateTimeZoneSource.GuessZoneIdByTransitionsUncached

---

src/NodaTime/Globalization/NodaFormatInfo.cs

This is a locally-rebased version of #634.
cc @BillWagner

Update format info to use C# 7 patterns

---

src/NodaTime.Web/Models/GoogleStorageReleaseRepository.cs
src/NodaTime.Web/Models/IReleaseRepository.cs
src/NodaTime.Web/Startup.cs

Web site fixes

---

src/NodaTime/Text/CompositePatternBuilder.cs

Even if we end up deciding we don't much like this API, it shouldn't
get in the way of creating a nicer one - and it does solve a problem
for now.
Fixes #607.

Make CompositePatternBuilder public.

---

build/buildapidocs.sh

- I was cloning the wrong repo
- I was receiving warnings due to putting command line
arguments the wrong way round then misreading the
warnings...

Fix docfx issues

---

src/NodaTime.Web/Markdown/2.0.x/index.json
src/NodaTime.Web/Markdown/2.0.x/versions.md
src/NodaTime.Web/Markdown/unstable/index.json
src/NodaTime.Web/Markdown/unstable/versions.md
src/NodaTime.Web/Views/Home/Index.cshtml

(None of this will be published until 2.0 is released.)

Minor website tweaks

---

src/NodaTime.Web/Markdown/root/versions.md

Add recent releases of TZDB updates to version history.

---

build/DocfxYamlLoader/DocfxMember.cs
build/DocfxYamlLoader/DocfxYamlLoader.csproj
build/DocfxYamlLoader/Release.cs
build/ReleaseDiffGenerator/Program.cs
build/ReleaseDiffGenerator/ReleaseDiffGenerator.csproj
build/Tools.sln
build/buildapidocs.sh
build/docfx/docfx.json

First pass at generating API diffs

---

build/DocfxYamlLoader/DocfxMember.cs
build/ReleaseDiffGenerator/Program.cs

Show types by kind (interface, struct etc) and then members by type.
Getting closing to finishing #732.

Better change display

---

src/NodaTime.Web/Startup.cs
src/NodaTime.Web/Web.config

I thought I'd removed the IIS-based redirection, but I hadn't...
so I hadn't been testing the one in code either, which was broken.
Fixes #753.

Fix redirect for latest API

---

src/NodaTime/TimeZones/BclDateTimeZone.cs

This would "fix" #746, providing what's likely to be more accurate
data anyway. On the other hand, it's making up data, which always
makes me nervous.
I've tested this on Mono on Linux (the only environment I expect to see it at the moment), and it reduces the failure count from 36 to 26 - it looks like it knocks out all those problems (leaving other ones which I think are really Mono issues).

Fake savings of 1 hour when TimeZoneInfo says the saving is 0 hours

---

src/NodaTime.Web/Startup.cs

(This has already been deployed :)

Go back to using GCS, and make it easily switched

---

src/NodaTime.Test/Text/Patterns/SteppedPatternBuilderTest.cs

This will then be fixed by #762.

Introduce test that deliberately fails

---

src/NodaTime/Text/Patterns/SteppedPatternBuilder.cs

Without knowing the intended behavior, I guess this is the intended code.

Repeated check

---

src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs

There are 14 broken tests on Mono for Linux; skipping
category BrokenOnMonoLinux will skip these. (They are
all due to bugs in Mono, as far as we can tell.) This
also skips tests for time zones which use Feb 29th in
any TimeZoneInfo rules due to another bug in Mono.
This helps narrow down #97.

Re-enable all time zones for Mono tests

---

src/NodaTime/Text/CompositePatternBuilder.cs
src/NodaTime/TimeZones/BclDateTimeZoneSource.cs

Add explicit public parameterless constructors.

---

src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/ZonedDateTime.cs

(More may be revealed when we fix #770.)

Document Era property non-nullability

---

src/NodaTime.Test/Annotations/MutabilityTest.cs
src/NodaTime.Test/Annotations/NullabilityTest.cs
src/NodaTime.Test/Annotations/PurityTest.cs
src/NodaTime.Test/Annotations/ReadWriteForEfficiencyTest.cs
src/NodaTime.Test/Annotations/ReflectionTest.cs
src/NodaTime.Test/Annotations/SecurityTest.cs
src/NodaTime.Test/Annotations/TrustedTest.cs
src/NodaTime.Test/TestHelper.cs
src/NodaTime/Annotations/TestExemptionAttribute.cs
src/NodaTime/Extensions/IsoDayOfWeekExtensions.cs
src/NodaTime/Instant.cs
src/NodaTime/Period.cs

- Make it simpler to do
- Add tests for names for conversions

Reflection-based testing

---

src/NodaTime.Web/Models/GoogleStorageReleaseRepository.cs
src/NodaTime.Web/Models/GoogleStorageTzdbRepository.cs
src/NodaTime.Web/Models/TimerCache.cs

This may or may not fix #755.
I've checked it out locally and it seems to do what we want. Will push it to the web site and we can see whether it improves things, then merge if so.

Use a timer-based cache on the web site

---

src/NodaTime.Web/Startup.cs
src/NodaTime.Web/Views/Shared/_Layout.cshtml

Add Cache-Control headers and cachebusting parameters to static content responses, as appropriate.
Fixes #794.

Provide sensible cache behaviour for static content

---

src/NodaTime.Test/LocalDateTest.Construction.cs
src/NodaTime/Calendars/GregorianYearMonthDayCalculator.cs

Validate non-positive day number in Gregorian calendar

---

src/NodaTime.Test/LocalTimeTest.Construction.cs
src/NodaTime/LocalTime.cs

Fixes #807.
(Another one to put in 2.0.1.)

Fix LocalTime construction validation

---

src/NodaTime.Test/LocalDateTest.Construction.cs
src/NodaTime.Test/LocalTimeTest.Construction.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/ZoneYearOffsetTest.cs
src/NodaTime/Calendars/GregorianYearMonthDayCalculator.cs
src/NodaTime/LocalTime.cs
src/NodaTime/TimeZones/ZoneYearOffset.cs

As described in #774.
(Timing for 2.0.1 still TBD.)

Cherry-picks for 2.0.1

---

src/NodaTime.Web/Markdown/2.0.x/migration-to-2.md
src/NodaTime.Web/Markdown/root/versions.md
src/NodaTime.Web/Markdown/unstable/migration-to-2.md

Document removal of IDateTimeZoneSource.MapTimeZoneId

---

src/NodaTime.Test/NodaTime.Test.csproj

Note that the use of Update rather than Include is crucial here.
See http://stackoverflow.com/questions/43846079

Use nesting for tests, as per old school msbuild

---

build/SnippetExtractor/BlockExtensions.cs
build/SnippetExtractor/Program.cs
build/SnippetExtractor/Snippet.cs
build/SnippetExtractor/SnippetExtractor.csproj
build/SnippetExtractor/SnippetFileSyntaxTree.cs
build/Tools.sln
build/buildapidocs.sh
build/docfx/template/partials/class.tmpl.partial
src/NodaTime.Demo/InstantDemo.cs
src/NodaTime.Demo/LocalDateDemo.cs
src/NodaTime.Demo/LocalDateTimeDemo.cs
src/NodaTime.Demo/LocalTimeDemo.cs
src/NodaTime.Demo/Snippet.cs
src/NodaTime.Demo/TimeZoneDemo.cs
src/NodaTime.Demo/ZonedDateTimeDemo.cs

Lots more to do, but the results are pretty nice.
Next steps:
- Write a blog post
- Use a script to make all the simplifications instead of adding
documents to the project
- Revisit all the Roslyn stuff
- Consider separating out into a new project

First pass at a snippet extractor

---

src/NodaTime.Test/Fields/TimePeriodFieldTest.cs
src/NodaTime/Calendars/HebrewYearMonthDayCalculator.cs
src/NodaTime/Calendars/RegularYearMonthDayCalculator.cs
src/NodaTime/Calendars/YearMonthDayCalculator.cs
src/NodaTime/Fields/FixedLengthDatePeriodField.cs
src/NodaTime/Fields/IDatePeriodField.cs
src/NodaTime/Fields/MonthsPeriodField.cs
src/NodaTime/Fields/TimePeriodField.cs
src/NodaTime/Fields/YearsPeriodField.cs
src/NodaTime/Period.cs

This follows on from #825, performing several refactorings afterwards.
I believe they will improve performance too, but I haven't validated that yet. They certainly make the code easier to understand, IMO.

Refactor period

---

src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime/NodaTime.csproj

(Will cherry-pick this into 2.0.x as well.)

Include source in symbol packages

---

build/runbenchmarks.sh

The intention is to run this in a cron job / scheduled task.

Script to run benchmarks from freshly-cloned repo

---

src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs

Add more benchmarks for Duration.From*

---

src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs

This will be merged immediately, before optimizations are merged, so
that the benchmark machines can show the improvements.

Add more benchmarks for Duration

---

src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs

(As the implementation of these parts might change.)

More benchmarks for Duration

---

src/NodaTime.Benchmarks/NodaTimeTests/DurationBenchmarks.cs
src/NodaTime.Test/DurationTest.Construction.cs
src/NodaTime/Duration.cs
src/NodaTime/Fields/TimePeriodField.cs

Duration optimizations

---

src/NodaTime/CalendarSystem.cs
src/NodaTime/Extensions/StopwatchExtensions.cs

Minor improvements noticed when working on 1.4.x

---

build/runbenchmarks.sh

Hard to really try this from where I am, but comments welcome...

Allow a --upload flag to upload benchmarks after running

---

src/NodaTime/DateInterval.cs

Fixes #878 when I've applied it to 2.0 as well.

Fix DateInterval docs

---

build/ReleaseDiffGenerator/Program.cs

Document newly-obsolete members

---

src/NodaTime.Test/LocalDateTest.cs
src/NodaTime/LocalDate.cs

Introduce LocalDate.Max/Min/MaxIsoValue/MinIsoValue

---

src/NodaTime.Test/LocalDateTest.cs
src/NodaTime/LocalDate.cs

Add LocalDate.{Min,Max}IsoValue

---

build/DocfxAnnotationGenerator/Program.cs

This is just a matter of applying the suggestions from Visual Studio to use C# 7's out variables.

Simplify annotation generator

---

src/NodaTime.Web/Markdown/2.0.x/text.md
src/NodaTime.Web/Markdown/2.1.x/text.md
src/NodaTime.Web/Markdown/2.2.x/text.md
src/NodaTime.Web/Markdown/unstable/text.md

Once this has been reviewed, I'll copy/paste the text into 2.0, 2.1
and 2.2. (Side-note: maybe we need a better way of keeping multiple
versions in sync where they haven't changed?)

First pass at clarifying custom/standard patterns

---

src/NodaTime.Web/Markdown/developer/roadmap.md

I think we're gradually running out of important things to do, which
is nice :)
(This PR will test the web site autopush, too. It should go live within about 45 minutes of being merged, assuming it's in UK daytime.)

Update the roadmap

---

.travis.yml
build/appveyor.sh
build/travis.sh
src/NodaTime-Web.sln
src/NodaTime.Web.Test/Models/StructuredVersionTest.cs
src/NodaTime.Web.Test/NodaTime.Web.Test.csproj
src/NodaTime.Web.Test/Program.cs
src/NodaTime.Web/Helpers/DictionaryExtensions.cs
src/NodaTime.Web/Helpers/NodaHtmlHelpers.cs
src/NodaTime.Web/Helpers/ProtobufConversions.cs
src/NodaTime.Web/Helpers/StringExtensions.cs
src/NodaTime.Web/Models/FakeReleaseRepository.cs
src/NodaTime.Web/Models/GoogleStorageBenchmarkRepository.cs
src/NodaTime.Web/Models/GoogleStorageReleaseRepository.cs
src/NodaTime.Web/Models/ReleaseDownload.cs
src/NodaTime.Web/Models/StructuredVersion.cs
src/NodaTime.Web/ViewModels/CompareTypesViewModel.cs
src/NodaTime.Web/Views/Downloads/Index.cshtml
src/NodaTime.Web/Views/Shared/_Layout.cshtml
src/NodaTime.Web/Views/_ViewImports.cshtml

I can break these out into separate changes if necessary...
- Move some web classes into a Helpers directory
- Add a VersionComparer to fix #905
- Add a test project for the web site
- Move Travis script into its own shell script in build, like AppVeyor
- Run web site tests on AppVeyor and Travis

A mixture of changes

---

.travis.yml
appveyor.yml
build/appveyor.sh
build/buildapidocs.sh
build/buildrelease.sh
build/buildweb.sh
build/travis.sh
global.json
src/NodaTime.Benchmarks/BclTests/TimeZoneInfoBenchmarks.cs
src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Benchmarks/NodaTimeTests/BclDateTimeZoneBenchmarks.cs
src/NodaTime.Test/Calendars/PersianCalendarSystemTest.cs
src/NodaTime.Test/Calendars/UmAlQuraYearMonthDayCalculatorTest.cs
src/NodaTime.Test/CultureSaver.cs
src/NodaTime.Test/DateTimeZoneProvidersTest.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/OffsetTest.cs
src/NodaTime.Test/TestHelper.cs
src/NodaTime.Test/Text/Cultures.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime.Web/NodaTime.Web.csproj

This will probably fail, as I'm pretty sure AppVeyor hasn't got VS 15.3, and I doubt that Travis has 2.0 yet. But it's nice to have it ready to try...

Move to .NET Core 2 SDK

---

src/NodaTime.Web/Controllers/BenchmarksController.cs
src/NodaTime.Web/Models/BenchmarkProtoPartials.cs
src/NodaTime.Web/Models/FakeBenchmarkRepository.cs
src/NodaTime.Web/Models/GoogleStorageBenchmarkRepository.cs
src/NodaTime.Web/Models/IBenchmarkRepository.cs
src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime.Web/ViewModels/CompareTypesViewModel.cs
src/NodaTime.Web/Views/Benchmarks/CompareTypes.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewBenchmark.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewBenchmarkHistory.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewRun.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewType.cshtml

Some tidying up, but new feature is to compare a type's benchmarks across two environments. This will allow us to compare netcoreapp1.0 and netcoreapp2.0 easily.

Benchmarking updates

---

src/NodaTime.Web/Helpers/NodaHtmlHelpers.cs
src/NodaTime.Web/Views/Benchmarks/Index.cshtml

Also tidy up the environment list slightly

Render durations as ns, us, ms or s.

---

src/NodaTime.Web/Models/GoogleStorageBenchmarkRepository.cs

Otherwise we get duplicate runs

Clone environments on change

---

.gitignore
appveyor.yml
build/appveyor.sh
build/coverage.sh
build/travis.sh
src/NodaTime.Test/coverageparams.xml

(Will modify github readme badge when we *have* some coverage.)

Reinstate code coverage using dotCover and codecov

---

src/NodaTime.Test/InstantTest.cs
src/NodaTime.Test/LocalInstantTest.cs
src/NodaTime/Instant.cs
src/NodaTime/LocalInstant.cs

Fix LocalInstant.SafeMinus near start/end of time

---

src/NodaTime/Duration.cs

This avoids a redundant argument range check, and looks like it
shaves off about 10% (under netcoreapp2.0 at least) on my machine.
Will merge so that we can see what it does with the nightly tests on
gabriel/bagpuss, and we can then back it out if necessary.

Experimental optimization for Duration.FromHours/Minutes/etc

---

src/NodaTime/TimeZones/PrecalculatedDateTimeZone.cs
src/NodaTime/Utility/HashCodeHelper.cs

Minor fixes

---

src/NodaTime.Test/InstantTest.Operators.cs
src/NodaTime/Instant.cs

Fix Instant - Duration not performing validation

---

src/NodaTime/CalendarSystem.cs
src/NodaTime/Calendars/IWeekYearRule.cs
src/NodaTime/Text/FormatHelper.cs

Replace <code> with <c> in XML comments

---

src/NodaTime/AnnualDate.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/Calendars/IWeekYearRule.cs
src/NodaTime/Text/FormatHelper.cs

Convert <code> to <c> for inline XML docs

---

build/DocfxAnnotationGenerator/Program.cs
build/buildapidocs.sh
build/buildhistory.sh
build/docfx_functions.sh
src/NodaTime/AnnualDate.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/Calendars/IWeekYearRule.cs
src/NodaTime/Text/FormatHelper.cs

(Builds on #990)
Will fix #865 when we backport to all previous branches, then rebuild the history.

Fix inline code references to use "c"

---

src/NodaTime.Demo/PeriodDemo.cs

OK, I'm submitting this very small PR just to see if I got this right.
I've just created a new test class in the Demo project and added a test to it, trying to imitate the other snippets in the project.
Is this it?
References #918

Creation of demo snippets for the 'Period' struct

---

src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime/OffsetDateTime.cs

Implement OffsetDateTime.InZone

---

src/NodaTime.Test/LocalDateTest.Conversion.cs
src/NodaTime.Test/LocalTimeTest.cs
src/NodaTime.Test/OffsetDateTest.cs
src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/OffsetTimeTest.cs
src/NodaTime.Test/Text/InstantPatternTest.cs
src/NodaTime.Test/Text/OffsetDatePatternTest.cs
src/NodaTime.Test/Text/OffsetTimePatternTest.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/LocalDate.cs
src/NodaTime/LocalTime.cs
src/NodaTime/OffsetDate.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs
src/NodaTime/Text/LocalTimePattern.cs
src/NodaTime/Text/OffsetDatePattern.cs
src/NodaTime/Text/OffsetDatePatternParser.cs
src/NodaTime/Text/OffsetTimePattern.cs
src/NodaTime/Text/OffsetTimePatternParser.cs
src/NodaTime/Text/Patterns/SteppedPatternBuilder.cs

(As suggested in #864.)
Current basic functionality is implemented, including text formatting parsing.
Conversions etc:
- OffsetDateTime.ToOffsetDate()
- OffsetDateTime.ToOffsetTime()
- LocalDate.WithOffset(Offset)
- LocalTime.WithOffset(Offset)
- OffsetDate.At(LocalTime)
- OffsetTime.On(LocalDate)
Still to be done: all serialization, documentation

OffsetDate and OffsetTime

---

src/NodaTime.Test/LocalDateTest.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime/LocalDate.cs

Implement deconstruction for LocalDate

---

build/tzdbupdate/update-2.0.sh
build/tzdbupdate/update-2.1.sh
build/tzdbupdate/update-2.2.sh

Make sure we package the release build for TZDB updates

---

src/NodaTime.Demo/PeriodDemo.cs

Added new snippets showing creation of periods via the `Between` method.
References #918.

Add more snippets to Period Demo class

---

src/NodaTime.Test/OffsetDateTest.cs
src/NodaTime.Test/OffsetTimeTest.cs
src/NodaTime/OffsetDate.cs
src/NodaTime/OffsetTime.cs

I think this completes the code changes for #864. We then need to do
documentation, and when 2.3 has been released we can look at
Json.NET support.

Implement serialization for OffsetDate and OffsetTime

---

src/NodaTime.Test/Calendars/WondrousCalendarSystemTest.cs
src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime/CalendarOrdinal.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/Calendars/Era.cs
src/NodaTime/Calendars/WondrousYearMonthDayCalculator.cs
src/NodaTime/Globalization/PatternResources.resx

@jskeet I'm not sure how to collapse these into a single commit. It took a number of attempts just to get it this far!  Feel free to do so if you can.

Add Wondrous calendar

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

Add union dateinterval

---

src/NodaTime.Test/Calendars/WondrousCalendarSystemTest.cs

- simplify the test file by removing the extension method
- test the helper functions

update test file

---

src/NodaTime.Web/Markdown/root/versions.md
src/NodaTime.Web/Markdown/unstable/calendars.md

Fixes #1045.
(Don't worry about reviewing the version doc, Glen - it's just about checking that the brief description of the Wondrous calendar system looks correct to you.)

Add documentation for Wondrous calendar and 2.3.0 features so far

---

src/NodaTime.Demo/DateIntervalDemo.cs

Add snippets for the DateInterval type

---

NuGet.config
build/SnippetExtractor/Program.cs
build/SnippetExtractor/Properties/launchSettings.json
build/SnippetExtractor/SnippetExtractor.csproj
build/SnippetExtractor/SnippetFileSyntaxTree.cs
build/SnippetExtractor/SnippetRewriter.cs
build/buildapidocs.sh
build/travis.sh
src/NodaTime.Demo/NodaTime.Demo.csproj

This is pretty horrible, but looks like it works, and with GA Roslyn
packages at that.
Fixes #1055.

Fix snippet generation

---

src/NodaTime.Web/Models/GoogleStorageReleaseRepository.cs
src/NodaTime.Web/Views/Home/Index.cshtml

Only display stable releases on front page

---

src/NodaTime.Web/Markdown/developer/building.md

At this point, I think we can close #765.

Tweaks for the "building" page

---

src/NodaTime.Web/Markdown/unstable/core-types.md
src/NodaTime.Web/Markdown/unstable/index.json
src/NodaTime.Web/Markdown/unstable/offsetdate-patterns.md
src/NodaTime.Web/Markdown/unstable/offsettime-patterns.md
src/NodaTime.Web/Markdown/unstable/serialization.md
src/NodaTime.Web/Markdown/unstable/type-choices.md
src/NodaTime.Web/NodaTime.Web.csproj

Minimal, but enough to specify text formats etc.
Fixes #864 - and unblocks a 2.3.0 release.

Documentation for OffsetTime and OffsetDate

---

src/NodaTime/LocalDate.cs
src/NodaTime/LocalDateTime.cs

Improve documentation for period arithmetic

---

src/NodaTime.Web/Markdown/developer/roadmap.md
src/NodaTime.Web/Markdown/root/versions.md
src/NodaTime.Web/Markdown/unstable/calendars.md

(This should also fix the incorrect display on non-ASCII characters, now I'm saving them as UTF-8.)

Finish the rename to Badi

---

data/cldr/windowsZones-33.xml

I'm not currently creating a new NZD file for this (or a new
release). We can do so if requested.

Add the CLDR v33 Windows Zones map

---

src/NodaTime.Test/InstantTest.Format.cs
src/NodaTime.Testing/TimeZones/MultiTransitionDateTimeZone.cs
src/NodaTime/CalendarSystem.cs
src/NodaTime/Text/InvalidPatternException.cs
src/NodaTime/Utility/Preconditions.cs
src/NodaTime/YearMonthDay.cs

Using C# 6 String Interpolation feature

---

src/NodaTime.TzdbCompiler/Tzdb/ParserHelper.cs
src/NodaTime.TzdbCompiler/Tzdb/Tokens.cs
src/NodaTime.TzdbCompiler/Tzdb/TzdbZoneInfoParser.cs
src/NodaTime.TzdbCompiler/Tzdb/TzdbZoneLocationParser.cs
src/NodaTime.TzdbCompiler/Tzdb/ZoneTransition.cs
src/NodaTime/Text/PeriodPattern.cs
src/NodaTime/TimeZones/PartialZoneIntervalMap.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs
src/NodaTime/ZonedDateTime.cs

Also clearing some whitespace, and removing/sorting usings

Using C# 6 nameof feature

---

src/NodaTime-Web.sln

This may well kill the web site again after build+deploy, but should leave us in a better place to diagnose it.

Add tools to solution file

---

src/NodaTime.Web/Views/Documentation/Docs.cshtml
src/NodaTime.Web/Views/Shared/_Layout.cshtml
src/NodaTime.Web/wwwroot/css/site.css

- Use blue/yellow/white for side-bar nav for user guide
- Move side-bar nav to left hand side
- Use side-bar rather than accordian for the user guide
- Remove the max-width set by Foundation

Adjust web site styling

---

src/NodaTime.Web/Views/Benchmarks/Index.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewBenchmark.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewBenchmarkHistory.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewEnvironment.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewRun.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewType.cshtml
src/NodaTime.Web/Views/Home/Docs.cshtml

Most of these are around benchmarks, which are harder to test
locally (on a mobile internet connection) - and which most users
won't look at anyway. Will merge then have a look at the result.

More styling changes

---

src/NodaTime.Test/DateIntervalTest.cs
src/NodaTime/DateInterval.cs

Make DateInterval iterable

---

src/NodaTime.Web/Markdown/2.0.x/recipes.md
src/NodaTime.Web/Markdown/developer/roadmap.md
src/NodaTime.Web/Markdown/root/versions.md

Also remove a TODO which shouldn't really be in the public docs

Update version/roadmap docs

---

build/buildhistory.sh

Fixes have been applied on the relevant branches.

Re-enable building snippets for 2.1.x and 2.2.x

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj

Update the dependencies at the same time

Include net461 as a target framework for benchmarks

---

build/BenchmarkUploader/BriefJsonModel.cs
build/BenchmarkUploader/Program.cs

(The JSON file format has changed a little.)

Update benchmark handling for latest BenchmarkDotNet

---

src/NodaTime-All.sln
src/NodaTime.Tools.DumpTimeZoneInfo/NodaTime.Tools.DumpTimeZoneInfo.csproj
src/NodaTime.Tools.DumpTimeZoneInfo/Program.cs

Will help diagnose #1140.
(It doesn't feel quite right in either src or build, but never mind.)

Add a tool to dump (relatively) raw TimeZoneInfo data

---

build/DocfxAnnotationGenerator/Program.cs
build/SnippetExtractor/Program.cs
build/SnippetExtractor/RewrittenSnippet.cs
build/SnippetExtractor/SnippetExtractor.csproj
build/SnippetExtractor/SnippetRewriter.cs
build/buildapidocs.sh
build/docfx/docfx-unstable.json
build/testsnippets.sh

(Will merge on green, and we'll see whether Bagpuss pushes it...)

Fix web site generation

---

src/NodaTime.Test/Ignore.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneSourceTest.cs
src/NodaTime.Test/TimeZones/BclDateTimeZoneTest.cs

Assume.That would work as well, but that would be less of a pure refactoring: it throws a different exception.

Add convenience method for ignoring tests conditionally

---

CONTRIBUTING.md
src/NodaTime.Web/Markdown/developer/building.md

Followed the instructions in `CONTRIBUTING.md` but found that you now need slightly different instructions to run the tests with the CLI.
Also slipstreamed two small readability updates in the same file.

Update CONTRIBUTING.md slightly

---

build/SnippetExtractor/RewrittenSnippet.cs
build/SnippetExtractor/SnippetRewriter.cs

I believe this is fixed due to #1153 being fixed - it certainly
seems to be okay...
Fixes #1145

Re-enable snippet output

---

src/NodaTime/Calendars/GJYearMonthDayCalculator.cs
src/NodaTime/Calendars/GregorianYearMonthDayCalculator.cs

Advice welcome on the second commit. (The first is trivial.)
- Can you think of useful benchmarks that might show this to be a good thing?
- If we can't detect any benefit but suspect there should be one, does it make sense to merge?
I was planning on merging to see whether the benchmarks *do* show anything.

(Experimental) A couple of optimizations

---

build/buildweb.sh
build/finishautobuildweb.sh
build/nodatime.org/Dockerfile
src/NodaTime.Web.Test/NodaTime.Web.Test.csproj
src/NodaTime.Web/NodaTime.Web.csproj

(This is required for Blazor integration.)

Update to ASP.NET Core 2.1

---

build/buildweb.sh
build/finishautobuildweb.sh

Once it's working in GKE, we'll try again on Azure...

Fix the slash properly, and temporarily disable push

---

src/NodaTime/Instant.cs
src/NodaTime/LocalDateTime.cs
src/NodaTime/OffsetDateTime.cs
src/NodaTime/OffsetTime.cs

This reduces the duplication around time calculations.

Refactor OffsetDateTime to use an OffsetTime

---

src/NodaTime.Web/Markdown/1.2.x/offsetdatetime-patterns.md
src/NodaTime.Web/Markdown/2.0.x/offsetdatetime-patterns.md
src/NodaTime.Web/Markdown/2.3.x/offsetdate-patterns.md
src/NodaTime.Web/Markdown/2.3.x/offsettime-patterns.md

Fix examples of using general offset format in compound patterns

---

src/NodaTime.Web.Blazor/NodaTime.Web.Blazor.csproj
src/NodaTime.Web.Blazor/Program.cs
src/NodaTime.Web.Blazor/Shared/NavMenu.cshtml
src/NodaTime.Web.Blazor/Startup.cs
src/NodaTime.Web.Blazor/wwwroot/index.html
src/NodaTime.Web/NodaTime.Web.csproj

Also change the way it's configured from NodaTime.Web to make it easier to include/exclude.

Update Blazor to 0.5.1

---

src/NodaTime.Web/Markdown/root/versions.md

Document the TZDB update policy

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

Fixes #1207
(No unit tests as the test would be far more involved than the change, and it's pretty risk-free. Let me know if you disagree :)

Order time zones by ID when guessing the system zone

---

src/NodaTime.Test/Calendars/BadiCalendarSystemTest.cs
src/NodaTime.Test/Calendars/HebrewCalendarSystemTest.cs
src/NodaTime.Test/LocalDateTest.PeriodArithmetic.cs
src/NodaTime.Web/Markdown/2.0.x/range.md
src/NodaTime/Calendars/BadiYearMonthDayCalculator.cs
src/NodaTime/Calendars/HebrewYearMonthDayCalculator.cs
src/NodaTime/Calendars/RegularYearMonthDayCalculator.cs

Fix PlusMonths to throw OverflowException when the result overflows

---

src/NodaTime.Benchmarks/NodaTimeTests/DateIntervalBenchmarks.cs
src/NodaTime/DateInterval.cs

Optimization for DateInterval.Contains, and benchmarks

---

src/NodaTime/Text/AnnualDatePatternParser.cs
src/NodaTime/Text/DurationPatternParser.cs
src/NodaTime/Text/InstantPatternParser.cs
src/NodaTime/Text/LocalDatePatternParser.cs
src/NodaTime/Text/LocalDateTimePatternParser.cs
src/NodaTime/Text/LocalTimePatternParser.cs
src/NodaTime/Text/OffsetDatePatternParser.cs
src/NodaTime/Text/OffsetDateTimePatternParser.cs
src/NodaTime/Text/OffsetPatternParser.cs
src/NodaTime/Text/OffsetTimePatternParser.cs
src/NodaTime/Text/Patterns/SteppedPatternBuilder.cs
src/NodaTime/Text/PeriodPattern.cs
src/NodaTime/Text/ZonedDateTimePatternParser.cs

These were originally the start of working on a standard extended-ISO pattern for LocalDateTime, but we're not quite there yet.

Improvements to text parsing internals

---

src/NodaTime.Web.Test/NodaTime.Web.Test.csproj
src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime.Web/Startup.cs

We now don't need to configure logging explicitly

Upgrade NodaTime.Web to netcoreapp2.2 and ASP.NET Core 2.2

---

build/SnippetExtractor/Program.cs
build/SnippetExtractor/SnippetExtractor.csproj
build/SnippetExtractor/app.config

This project seriously needs some love at some point, ideally in a
way that will allow it to run on .NET Core too. For the moment,
let's just get the build working again.

Fix (hopefully...) the snippet extractor on Bagpuss

---

build/SnippetExtractor/SnippetExtractor.csproj

(This should have been in the previous commit.)

Use .NET 4.7.2 for SnippetExtractor

---

src/NodaTime/Duration.cs

Fixes #1258. (It will take a little while for the web site to catch up though.)

Fix documentation inversion

---

src/NodaTime.Web/Markdown/2.4.x/limitations.md

Fixes #1273 (as far as that's going to be fixed)
(This won't show up on the web site until tomorrow.)

Create new limitations doc which clarifies .NET Standard 2.0 support

---

build/buildrelease.sh
src/NodaTime.Web/Markdown/root/versions.md

(This may well not work first time...)

Prepare for 3.0-alpha01 release

---

build/buildrelease.sh
src/NodaTime.Test/Utility/PreconditionsTest.cs
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime/NodaTime.csproj

- PreconditionsTest had a nullability issue when building in release
- The release script had a couple of typos in
- Package licensing is changing

Changes noticed when building 3.0.0-alpha01

---

src/NodaTime.Web/Controllers/TzValidateController.cs
src/NodaTime.Web/Models/GoogleStorageTzdbRepository.cs

- Cache read-through for TZDB releases
- TZValidate features (zone and version)

Web site improvements

---

src/NodaTime.Web/Views/Benchmarks/CompareTypesByCommit.cshtml
src/NodaTime.Web/Views/Benchmarks/CompareTypesByEnvironment.cshtml
src/NodaTime.Web/Views/Benchmarks/Index.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewBenchmark.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewBenchmarkHistory.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewEnvironment.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewRun.cshtml
src/NodaTime.Web/Views/Benchmarks/ViewType.cshtml
src/NodaTime.Web/wwwroot/css/site.css

Changes done under this : 
- Added Breadcrumb on benchmark related screen for proper navigations 
- Moved the view hyperlink on right side of table
- Fixed a hieght issue , where footer was coming in between screen and not sticking in bottom

Fixes #937

---

build/deploytestbuild.sh
build/nodatime.org/testcloudbuild.yaml

Note that this will only work if you have access, which realistically means "Jon only" for now.

Add scripts and Cloud Build file for deploying to test.nodatime.org

---

src/NodaTime.Web/Markdown/2.3.x/serialization.md

Add note on ASP.NET Core configuration for JSON.

---

build/deploytestbuild.sh
build/nodatime.org/testdeployment.yaml
src/NodaTime.Web/Startup.cs

Tested with test.nodatime.org. Seems to work fine.

Fix HTTPS issues for nodatime.org

---

src/NodaTime.Web/Startup.cs

Add healthz path, which doesn't get HTTPS redirection

---

src/NodaTime.Web/Configuration/StackdriverOptions.cs
src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime.Web/Program.cs
src/NodaTime.Web/Startup.cs
src/NodaTime.Web/appsettings.Production.json
src/NodaTime.Web/appsettings.Staging.json
src/NodaTime.Web/appsettings.json

This isn't as clean as I'd like it to be, but it looks like it works.

Add Stackdriver integration

---

src/NodaTime.Web/Configuration/NetworkOptions.cs
src/NodaTime.Web/Configuration/StackdriverOptions.cs
src/NodaTime.Web/Startup.cs
src/NodaTime.Web/appsettings.Production.json
src/NodaTime.Web/appsettings.Staging.json
src/NodaTime.Web/appsettings.json

This is a bit ugly because of the duplication between Production and
Staging, admittedly.

Configure header forwarding etc via appsettings.json

---

src/NodaTime.Test/Globalization/NodaFormatInfoTest.cs
src/NodaTime.Test/TimeZones/IO/DtzIoHelper.cs
src/NodaTime/Calendars/EraCalculator.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/Text/Patterns/DatePatternHelper.cs
src/NodaTime/Text/Patterns/SteppedPatternBuilder.cs
src/NodaTime/TimeZones/IO/DateTimeZoneReader.cs
src/NodaTime/TimeZones/IO/TzdbStreamData.cs
src/NodaTime/TimeZones/IO/TzdbStreamField.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

Fixes #1350 as far as we want to

Use read-only interfaces where feasible internally

---

src/NodaTime.Demo/YearMonthDemo.cs

Some demo tests, covering mainly construction of YearMonth instances.

Add snippet for YearMonth type

---

src/NodaTime.Test/LocalTimeTest.Construction.cs
src/NodaTime/LocalTime.cs

Fixes #1366
(FromHoursSinceMidnight is a little less useful, but I've included it for consistency/completeness.)

Add LocalTime.FromHoursSinceMidnight and FromMinutesSinceMidnight

---

CONTRIBUTING.md

update the name of the solution in the contributing guidelines

Update the name of the solution in the contributing guidelines

---

src/NodaTime.Demo/OffsetDateTimeDemo.cs

I intend to add some more later.
[UPDATE] Added some more snippets, and fixed some mistakes that I had made in the previous ones. Squashed and force-pushed.

Add some snippets for the 'OffsetDateTime' type

---

src/NodaTime.Demo/TimeZoneDemo.cs

Make TimeZoneDemo work when running in different cultures

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime.Tools.ValidateHistoricalNzd/NodaTime.Tools.ValidateHistoricalNzd.csproj
src/NodaTime.Tools.ValidateHistoricalNzd/Program.cs
src/NodaTime.sln
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

Hopefully this is the last of it...

Yet more TZDB Windows zones validation

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs

These are canonicalized, and handle cases such as an alias being present but not the canonical ID, or vice versa.
Fixes #274

Provide dictionaries from TZDB ID to Windows ID and vice versa

---

src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj

This should make the filtered tests run much quicker.

Update NUnit test adapter

---

src/NodaTime.Demo/LocalDateDemo.cs
src/NodaTime.Demo/PeriodBuilderDemo.cs

Hi @jskeet 
In reference to #918, I've started looking at contributing to your snippets library. This is a small PR just to get the green light from yourself that I've understood the requirements for your snippet generation.
Feel free to comment with a thumbs up that I'm on the right track, or merge and I'll create a new PR with any new, fresh snippets.

Expanded snippets

---

src/NodaTime.Demo/DateAdjustersDemo.cs

Adds tests with snippets to `DateAdjusters` as per #918.

Adds snippets to DateAdjusters

---

src/NodaTime.Demo/LocalDateDemo.cs

Add snippet for Max and Min for LocalDate

---

src/NodaTime.Demo/PeriodDemo.cs

Adds snippets for `Normalize()` and `ToDuration()` in `PeriodDemo` as per #918.

Adds snippets to Period

---

src/NodaTime.Demo/LocalDateDemo.cs

Add snippets for LocalDate method Add and CompareTo

---

src/NodaTime.Demo/LocalDateDemo.cs

Add snippet for Equals

---

src/NodaTime.Demo/LocalDateDemo.cs

Add snippet for Equals(Object)

---

src/NodaTime.Demo/IntervalDemo.cs

Added snippets for Interval.Deconstruct(out Instant, out Instant), Interval.Duration and Interval.ToString()

Added snippets for [Interval] Deconstruct, Duration and ToString()

---

src/NodaTime.Benchmarks/NodaTimeTests/LocalDateBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/LocalDateTimeBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/Text/InstantPatternBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/Text/LocalDatePatternBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/Text/LocalDateTimePatternBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/Text/OffsetDateTimePatternBenchmarks.cs
src/NodaTime.Benchmarks/NodaTimeTests/Text/ZonedDateTimePatternBenchmarks.cs
src/NodaTime.Demo/LocalDateDemo.cs
src/NodaTime.Demo/LocalDateTimeDemo.cs
src/NodaTime.NzdPrinter/Program.cs
src/NodaTime.Test/Calendars/BclEquivalenceHelper.cs
src/NodaTime.Test/Calendars/HebrewCalendarSystemTest.cs
src/NodaTime.Test/LocalDateTimeTest.Pseudomutators.cs
src/NodaTime.Test/OffsetDateTest.cs
src/NodaTime.Test/OffsetDateTimeTest.cs
src/NodaTime.Test/Text/CompositePatternBuilderPatternTest.cs
src/NodaTime.Test/Text/InstantPatternTest.cs
src/NodaTime.Test/Text/LocalDatePatternTest.cs
src/NodaTime.Test/Text/LocalDateTimePatternTest.cs
src/NodaTime.Test/Text/OffsetDatePatternTest.cs
src/NodaTime.Test/Text/OffsetDateTimePatternTest.cs
src/NodaTime.Test/Text/YearMonthPatternTest.cs
src/NodaTime.Test/Text/ZonedDateTimePatternTest.cs
src/NodaTime.Test/ZonedDateTimeTest.cs
src/NodaTime.TzValidate.NzdCompatibility/ZoneDumper.cs

Update "yyyy" to "uuuu" in tests/benchmarks/demos

---

src/NodaTime/AnnualDate.cs

Implement IComparable for AnnualDate

---

src/NodaTime.TzdbCompiler/Program.cs

Update old twinsun link to use IANA

---

data/cldr/windowsZones-36.xml

Add CLDR v36 Windows / IANA zone mappings

---

src/NodaTime.Test/Text/YearMonthPatternTest.cs
src/NodaTime/Calendars/HebrewScripturalCalculator.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/Text/Patterns/PatternBclSupport.cs
src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs
src/NodaTime/Utility/Preconditions.cs

I'm *slightly* worried by the change from using StandardName to Id for the cache, but I think it's okay.
(I don't think Mono actually returns "Local" for the time zone ID anyway now.)

Fix or remove TODOs

---

src/NodaTime.Test/YearMonthTest.Misc.cs
src/NodaTime/YearMonth.cs

Add YearMonth.OnDayOfMonth

---

src/NodaTime.Demo/OffsetDemo.cs

First pull request to make sure I follow the conventions.

Added a snippet for Max method in OffsetDemo

---

src/NodaTime.Demo/OffsetDemo.cs

Added snippets for missing methods of Offset.

Added snippets for OffsetDemo in Demo

---

src/NodaTime.NzdPrinter/Program.cs
src/NodaTime.Tools.Common/FileUtility.cs
src/NodaTime.TzValidate.NodaDump/Program.cs
src/NodaTime.TzValidate.NzdCompatibility/Program.cs

It's very easy to adapt command line tools since C# 7.1 and async Main support.

Make LoadFileOrUrl truly async

---

src/NodaTime.Demo/AnnualDateDemo.cs

+AnnualDateDemo.cs in NodaTime.Demo

Added AnnualDate snippets in Demo

---

src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime/NodaTime.csproj

Use PackageLicenseExpression in packages in 2.4.x

---

Directory.Build.targets
build/buildrelease.sh
build/tzdbupdate/update-2.4.sh
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime/NodaTime.csproj

(We should do this for serialization as well at some point...)
Fixes #1510.

Update package builds for SourceLink

---

build/tzdbupdate/update-master.sh
src/NodaTime.Test/Xml/XmlSchemaTest.XmlSchema.approved.xml
src/NodaTime.TzdbCompiler/CompilerOptions.cs
src/NodaTime.TzdbCompiler/Program.cs

Update the expected XML schema as part of TZDB generation

---

Directory.Build.props
build/BenchmarkUploader/BenchmarkUploader.csproj
build/Directory.Build.props
build/Directory.Build.targets
build/HashStorageFiles/HashStorageFiles.csproj
build/NullableApiReviewer/NullableApiReviewer.csproj
build/NullableApiReviewer/Program.cs
src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.NzdPrinter/NodaTime.NzdPrinter.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Testing/NodaTime.Testing.csproj
src/NodaTime.Tools.Common/NodaTime.Tools.Common.csproj
src/NodaTime.Tools.DumpTimeZoneInfo/NodaTime.Tools.DumpTimeZoneInfo.csproj
src/NodaTime.Tools.ValidateHistoricalNzd/NodaTime.Tools.ValidateHistoricalNzd.csproj
src/NodaTime.TzValidate.NodaDump/NodaTime.TzValidate.NodaDump.csproj
src/NodaTime.TzValidate.NzdCompatibility/NodaTime.TzValidate.NzdCompatibility.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime.sln
src/NodaTime/NodaTime.csproj

This massively reduces the amount of duplication between projects.

Tweaks to projects

---

src/NodaTime.Benchmarks/NodaTimeTests/LocalDateBenchmarks.cs
src/NodaTime/LocalDate.cs
src/NodaTime/YearMonth.cs

Only the last commit is relevant here - the first two are from #1530.

Improve performance of LocalDate and YearMonth comparisons

---

Directory.Build.props

See https://nodatime.org/versions for release notes

Release Noda Time version 3.0.0

---

src/NodaTime.Testing/NodaTime.Testing.csproj

Generate documentation for NodaTime.Testing

---

src/NodaTime/OffsetDateTime.cs
src/NodaTime/Text/OffsetDatePattern.cs
src/NodaTime/Text/OffsetDateTimePattern.cs
src/NodaTime/Text/OffsetTimePattern.cs

Found this, while "browsing Intellisense".

Changed "zoned" to "offset" where it was wrongly used

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime/DateInterval.cs
src/NodaTime/Fields/FixedLengthDatePeriodField.cs
src/NodaTime/Period.cs

An attempt at addressing #1450.

Add 'DaysBetween' method to Period

---

data/cldr/windowsZones-37.xml

Note that this still has the same problem as v36 in terms of the
revision, as noted in #1559.

Add CLDR v37 mapping data

---

src/NodaTime/TimeZones/ZoneInterval.cs

This is in line with the other properties.

Document ZoneInterval.Start behavior for "to start of time"

---

src/NodaTime.Demo/LocalDateDemo.cs

Add snippet for Day, DayOfWeek and DayOfYear.
Ref: #918

Add snippet for Day, DayOfWeek and DayOfYear

---

src/NodaTime.Demo/LocalDateDemo.cs

Add snippet for next

---

build/tzdbupdate/update-3.0.sh

Skip updating the XML schema test file in 3.0.x

---

src/NodaTime.Benchmarks/NodaTimeTests/LocalTimeBenchmarks.cs
src/NodaTime.Test/Extensions/TimeOnlyExtensionsTest.cs
src/NodaTime.Test/LocalTimeTest.Conversion.cs
src/NodaTime/Extensions/TimeOnlyExtensions.cs
src/NodaTime/LocalTime.cs

Implement TimeOnly support for .NET 6

---

Directory.Build.props

This is effectively a test of the new release GitHub action

First release candidate for 3.1.0

---

Directory.Build.props

Second release candidate; only change is in the release GitHub action

Release 3.1.0-rc.2

---

build/Tools.sln

This was intended to be in the previous commit - I just failed to
save the solution...

Remove HashStorageFiles from tools solution

---

src/NodaTime/CalendarSystem.cs

Swap documentation for Persian calendar properties

---

src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs

... and exclude Iran, which is currently broken.

Make it easier to exclude time zones from guessing test

---

src/NodaTime.Demo/XmlSchemaDemo.XmlSchemaClassGeneratorAssemblyCreator.cs
src/NodaTime.Demo/XmlSchemaDemo.cs

It was skipped in b81a841850fb6935cd2f907e908958ea4f90c15b

Re-enable the DynamicCodeGeneration test

---

src/NodaTime.Benchmarks.Custom/ConcurrencyCommandBase.cs
src/NodaTime.Benchmarks.Custom/ConcurrentNewString.cs
src/NodaTime.Benchmarks.Custom/ConcurrentNoOp.cs
src/NodaTime.Benchmarks.Custom/ConcurrentPatternFormat.cs
src/NodaTime.Benchmarks.Custom/ConcurrentToString.cs
src/NodaTime.Benchmarks.Custom/ConfigurationException.cs
src/NodaTime.Benchmarks.Custom/NodaTime.Benchmarks.Custom.csproj
src/NodaTime.Benchmarks.Custom/Program.cs
src/NodaTime.Test/Globalization/NodaFormatInfoTest.cs
src/NodaTime.sln
src/NodaTime/Duration.cs
src/NodaTime/Globalization/NodaFormatInfo.cs
src/NodaTime/TimeZones/FixedDateTimeZone.cs

There are a couple of other minor changes in here, in separate commits. I thought it easiest to get them reviewed together. It'll be easiest to review one commit at a time.

Improve performance for concurrent formatting

---

src/NodaTime.Test/InstantTest.cs
src/NodaTime/Instant.cs

Add Instant.ToUnixTimeSecondsAndNanoseconds

---

src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj
src/NodaTime.Demo/NodaTime.Demo.csproj
src/NodaTime.NzdPrinter/NodaTime.NzdPrinter.csproj
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj
src/NodaTime.TzdbCompiler.Test/Tzdb/TzdbZoneInfoParserTest.cs
src/NodaTime.TzdbCompiler/NodaTime.TzdbCompiler.csproj
src/NodaTime/NodaTime.csproj

This doesn't yet update us to NUnit v4 - that will be a bigger change, given that the assertion style has changed.

Update dependencies in all projects

---

src/NodaTime.Test/GlobalUsings.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime.Test/TimeZones/TzdbDateTimeZoneSourceTest.cs
src/NodaTime.TzdbCompiler.Test/GlobalUsings.cs
src/NodaTime.TzdbCompiler.Test/NodaTime.TzdbCompiler.Test.csproj

I've opted to stick with the "classic" assertion style, and use global using directives to make that painless.

Upgrade to NUnit 4

---

Directory.Build.targets

(SourceLink is built into the .NET 8 SDK.)

Update SauceControl.InheritDoc; remove SourceLink target

---

src/NodaTime/NodaTime.csproj

Conditionalize the dependency on System.Runtime.CompilerServices.Unsafe.

---

src/NodaTime/Text/AnnualDatePattern.cs
src/NodaTime/Text/DurationPattern.cs
src/NodaTime/Text/LocalDatePattern.cs
src/NodaTime/Text/LocalTimePattern.cs
src/NodaTime/Text/OffsetPattern.cs
src/NodaTime/Text/YearMonthPattern.cs

Remove nonsensical aspect of capture for invariant methods.

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime/Period.cs
src/NodaTime/Text/PeriodPattern.cs

feat: add Period.MinValue and Period.MaxValue

---

src/NodaTime.Test/DurationTest.Operators.cs
src/NodaTime.Test/OffsetTest.cs
src/NodaTime.Test/PeriodTest.cs
src/NodaTime.Test/TestHelper.cs
src/NodaTime/Offset.cs

(Just trivial tests and moving a member really.)

Tweaks to generic operators

---

src/NodaTime.Test/Annotations/ReflectionTest.cs
src/NodaTime.Test/Extensions/TimeProviderExtensionsTest.cs
src/NodaTime.Test/NodaTime.Test.csproj
src/NodaTime/Extensions/TimeProviderExtensions.cs

This adds:
- ToClock
- ToZonedClock (with and without calendar system)
- GetCurrentInstant
First steps towards #1751 (and may be all we ever do).
/cc @jennings @patrikwlund

Add TimeProvider extension methods

---

src/NodaTime.Test/PeriodTest.cs
src/NodaTime/Period.cs

Add NanosecondsBetween method to Period
